"""BMJ Publishing Group journals and VIP format template.

BMJ Publishing Group publishes a wide range of medical journals,
all hosted on bmj.com subdomains using the VIP format.
"""

# VIP template for BMJ journals
bmj_vip_template = {
    'url_template': 'http://{host}/content/{volume}/{issue}/{first_page}.full.pdf',
    'required_fields': ['volume', 'issue', 'first_page'],
    'host_param': 'host'
}

# BMJ journals with their host parameters
bmj_journals = [
    'Acupunct Med',
    'Arch Dis Child', 
    'Arch Dis Child Fetal Neonatal Ed',
    'Arch Dis Child Educ Pract Ed',
    'Ann Rheum Dis',
    'BMJ Innov',
    'BMJ Open',
    'BMJ Open Diabetes Res Care',
    'BMJ Open Resp Res',
    'BMJ Open Sport Exerc Med',
    'BMJ Qual Saf',
    'BMJ Qual Improv Report',
    'BMJ STEL',
    'BMJ Support Palliat Care',
    'BMC Ophthalmol',
    'Br J Sports Med',
    'Drug Ther Bull',
    'Emerg Med J',
    'End Life J',
    'ESMO Open',
    'Eur J Hosp Pharm',
    'Evid Based Mental Health',
    'Evid Based Med',
    'Evid Based Nurs',
    'Frontline Gastroenterol',
    'Gut',
    'Heart',
    'Heart Asia',
    'Inj Prev',
    'In Pract',
    'J Clin Pathol',
    'J Epidemiol Community Health',
    'J Fam Plann Reprod Health Care',
    'J Investig Med',
    'J ISAKOS',
    'J Med Ethics',
    'J Med Genet',
    'J Neurol Neurosurg Psychiatry',
    'J Neurointerv Surg',
    'J R Army Med Corps',
    'Lupus Sci Med',
    'Med Humanities',
    'Occup Environ Med',
    'Open Heart',
    'Pract Neurol',
    'RMD Open',
    'Sex Transm Infect',
    'Vet Rec',
    'Vet Rec Case Rep',
    'Vet Rec Open',
    'Tob Control',
    'Postgrad Med J',
    'Thorax',
]

# Host parameters for each BMJ journal
bmj_journal_params = {
    'Acupunct Med': {'host': 'aim.bmj.com'},
    'Arch Dis Child': {'host': 'adc.bmj.com'},
    'Arch Dis Child Fetal Neonatal Ed': {'host': 'fn.bmj.com'},
    'Arch Dis Child Educ Pract Ed': {'host': 'ep.bmj.com'},
    'Ann Rheum Dis': {'host': 'ard.bmj.com'},
    'BMJ Innov': {'host': 'innovations.bmj.com'},
    'BMJ Open': {'host': 'bmjopen.bmj.com'},
    'BMJ Open Diabetes Res Care': {'host': 'drc.bmj.com'},
    'BMJ Open Resp Res': {'host': 'bmjopenrespres.bmj.com'},
    'BMJ Open Sport Exerc Med': {'host': 'bmjopensem.bmj.com'},
    'BMJ Qual Saf': {'host': 'qualitysafety.bmj.com'},
    'BMJ Qual Improv Report': {'host': 'qir.bmj.com'},
    'BMJ STEL': {'host': 'stel.bmj.com'},
    'BMJ Support Palliat Care': {'host': 'spcare.bmj.com'},
    'BMC Ophthalmol': {'host': 'bjo.bmj.com'},
    'Br J Sports Med': {'host': 'bjsm.bmj.com'},
    'Drug Ther Bull': {'host': 'dtb.bmj.com'},
    'Emerg Med J': {'host': 'emj.bmj.com'},
    'End Life J': {'host': 'eolj.bmj.com'},
    'ESMO Open': {'host': 'esmoopen.bmj.com'},
    'Eur J Hosp Pharm': {'host': 'ejhp.bmj.com'},
    'Evid Based Mental Health': {'host': 'ebmh.bmj.com'},
    'Evid Based Med': {'host': 'ebm.bmj.com'},
    'Evid Based Nurs': {'host': 'ebn.bmj.com'},
    'Frontline Gastroenterol': {'host': 'fg.bmj.com'},
    'Gut': {'host': 'gut.bmj.com'},
    'Heart': {'host': 'heart.bmj.com'},
    'Heart Asia': {'host': 'heartasia.bmj.com'},
    'Inj Prev': {'host': 'injuryprevention.bmj.com'},
    'In Pract': {'host': 'inpractice.bmj.com'},
    'J Clin Pathol': {'host': 'jcp.bmj.com'},
    'J Epidemiol Community Health': {'host': 'jech.bmj.com'},
    'J Fam Plann Reprod Health Care': {'host': 'jfprhc.bmj.com'},
    'J Investig Med': {'host': 'jim.bmj.com'},
    'J ISAKOS': {'host': 'jisakos.bmj.com'},
    'J Med Ethics': {'host': 'jme.bmj.com'},
    'J Med Genet': {'host': 'jmg.bmj.com'},
    'J Neurol Neurosurg Psychiatry': {'host': 'jnnp.bmj.com'},
    'J Neurointerv Surg': {'host': 'jnis.bmj.com'},
    'J R Army Med Corps': {'host': 'jramc.bmj.com'},
    'Lupus Sci Med': {'host': 'lupus.bmj.com'},
    'Med Humanities': {'host': 'mh.bmj.com'},
    'Occup Environ Med': {'host': 'oem.bmj.com'},
    'Open Heart': {'host': 'openheart.bmj.com'},
    'Pract Neurol': {'host': 'pn.bmj.com'},
    'RMD Open': {'host': 'rmdopen.bmj.com'},
    'Sex Transm Infect': {'host': 'sti.bmj.com'},
    'Vet Rec': {'host': 'veterinaryrecord.bmj.com'},
    'Vet Rec Case Rep': {'host': 'vetrecordcasereports.bmj.com'},
    'Vet Rec Open': {'host': 'vetrecordopen.bmj.com'},
    'Tob Control': {'host': 'tobaccocontrol.bmj.com'},
    'Postgrad Med J': {'host': 'pmj.bmj.com'},
    'Thorax': {'host': 'thorax.bmj.com'},
}