"""
De Gruyter publisher configuration.

Academic publisher with journals across sciences and humanities.
DOI-based PDF access for journals with 10.1515 DOI prefix.
"""

from __future__ import absolute_import, unicode_literals

# De Gruyter template for DOI-based access
degruyter_template = 'https://www.degruyter.com/document/doi/{doi}/pdf'

degruyter_journals = (
    # Original journals
    'Arh Hig Rada Toksikol',
    'Clin Chem Lab Med',
    'J Pediatr Endocrinol Metab',
    'Horm Mol Biol Clin Investig',
    
    # Additional journals from categorized_unknown_journals.txt analysis
    'Addict Genet',
    'Adv Alzheimer Dis',
    'Adv Appl Sociol',
    'Adv Breast Cancer Res',
    'Adv Enzyme Res',
    'Adv Infect Dis',
    'Adv J Mol Imaging',
    'Adv Microbiol',
    'Am J Clim Change',
    'Am Mineral',
    'Apeiron',
    'Appl Math',
    'Aschkenas',
    'B E J Econom Anal Policy',
    'Bioinorg React Mech',
    'Biol Chem',
    'Biol Chem Hoppe Seyler',
    'Biomed Tech (Berl)',
    'Biomol Concepts',
    'Botanica Marina',
    'Cent Eur J Biol',
    'Cent Eur J Med',
    'Chem Teach Int',
    'Cogn Linguist',
    'Comput Math Biophys',
    'Contrib Econ Analysis Policy',
    'Creat Educ',
    'Diabet Nephrop',
    'Diagnosis',
    'Drug Metab Pers Ther',
    'Drug Metabol Drug Interact',
    'Endoplasmic Reticulum Stress Dis',
    'Epidemiol Methods',
    'Eur J Nanomed',
    'Forum Health Econ Policy',
    'Front Health Policy Res',
    'Ger Econ Rev',
    'Health N Hav',
    'Heterocycl Comm',
    'Holzforschung',
    'Hoppe Seylers Z Physiol Chem',
    'IRAL Int Rev Appl Linguist Lang Teach',
    'Innov Surg Sci',
    'Int J Adolesc Med Health',
    'Int J Biostat',
    'Int J Disabil Hum Dev',
    'Int J Nurs Educ Scholarsh',
    'Int J Org Chem',
    'Int J Soc Lang',
    'Int Polym Process',
    'Intell Inf Manag',
    'J Agric Food Ind Organ',
    'J Am Osteopath Assoc',
    'J Biomed Sci Eng',
    'J Causal Inference',
    'J Coll Character',
    'J Complement Integr Med',
    'J Comput Methods Appl Math',
    'J Diabetes Mellitus',
    'J Drug Policy Anal',
    'J Econom Method',
    'J Homel Secur Emerg Manag',
    'J Integr Bioinform',
    'J Inverse Ill Posed Probl',
    'J Mech Behav Mater',
    'J Perinat Med',
    'J Quant Anal Sports',
    'J Surf Eng Mater Adv Technol',
    'J Transl Int Med',
    'J Tuberc Res',
    'Jahrb Natl Okon Stat',
    'Linguist Vanguard',
    'Low Carbon Econ',
    'Mammalia',
    'Med Genet',
    'Mesoporous Biomater',
    'Mod Res Inflamm',
    'Mol Based Math Biol',
    'Monte Carlo Methods Appl',
    'Nanofabrication',
    'Nanophotonics',
    'Nanotechnol Rev',
    'Nat Sci',
    'Nord Pulp Paper Res J',
    'Open Agric',
    'Open Chem',
    'Open J Anesthesiol',
    'Open J Anim Sci',
    'Open J Apoptosis',
    'Open J Biophys',
    'Open J Clin Diagn',
    'Open J Endocr Metab Dis',
    'Open J Epidemiol',
    'Open J Genet',
    'Open J Inorg Chem',
    'Open J Med Chem',
    'Open J Med Microbiol',
    'Open J Mol Integr Physiol',
    'Open J Ophthalmol',
    'Open J Orthop',
    'Open J Pediatr',
    'Open J Polit Sci',
    'Open J Rheumatol Autoimmune Dis',
    'Open J Stat',
    'Open J Vet Med',
    'Open Life Sci',
    'Open Linguist',
    'Open Psychol',
    'Paladyn',
    'Pharm Technol Hosp Pharm',
    'Phonetica',
    'Photonics Lasers Med',
    'Pleura Peritoneum',
    'Psychology',
    'Pteridines',
    'Pure Appl Chem',
    'Q Rev Drug Metab Drug Interact',
    'Radiochim Acta',
    'Rev Anal Chem',
    'Rev Drug Metab Drug Interact',
    'Rev Environ Health',
    'Rev Neurosci',
    'Scand J Pain',
    'Semiotica',
    'Stat Appl Genet Mol Biol',
    'Stat Commun Infect Dis',
    'Stat Politics Policy',
    'Stud Ethics Law Technol',
    'Surg Sci',
    'Theor Linguist',
    'Top Econ Anal Policy',
    'Transl Neurosci',
    'World J Cardiovasc Surg',
    'Z Aegypt Sprach Altertumskd',
    'Z Kristallogr Cryst Mater',
    'Z Nat Forsch A J Phys Sci',
    'Z Naturforsch B Anorg Chem Org Chem Biochem Biophys Biol',
    'Z Naturforsch C',
    'Z Naturforsch C Biosci',
    'Z Naturforsch C J Biosci',
    'Z Phys Chem (N F)',
    'Z Rom Philol',
)
