"""
Mary Ann Liebert Publishers journal patterns and mappings.

Liebert publishes biomedical journals using DOI-based URLs with a 
standardized format across all their publications.

URL Pattern: http://online.liebertpub.com/doi/pdf/{doi}
Dance Function: the_doi_slide
"""

# Publisher metadata
PUBLISHER_INFO = {
    'name': 'Mary Ann Liebert Publishers',
    'dance_function': 'the_doi_slide',
    'base_url': 'https://liebertpub.com',
    'url_pattern': 'http://online.liebertpub.com/doi/pdf/{doi}',
    'identifier_type': 'doi'  # DOI-based format
}

# Liebert journals using DOI format (expanded from unknown publishers analysis)
liebert_journals = [
    # Original 8 journals
    'AIDS Res Hum Retroviruses',
    'Antioxid Redox Signal', 
    'Child Obes',
    'DNA Cell Biol',
    'Genet Test',
    'Genet Test Mol Biomarkers',
    'Thyroid',
    'Vector Borne Zoonotic Dis',
    
    # Additional Liebert journals from unknown publishers analysis (189 journals)
    '3D Print Addit Manuf',
    'AIDS Patient Care STDS',
    'AIDS Res',
    'Adv Wound Care',
    'Altern Complement Ther',
    'Androg Clin Res Ther',
    'Antisense Nucleic Acid Drug Dev',
    'Antisense Res Dev',
    'Appl Biosaf',
    'Appl In Vitro Toxicol',
    'Assay Drug Dev Technol',
    'Astrobiology',
    'Autism Adulthood',
    'Bariatr Surg Pract Patient Care',
    'Big Data',
    'Bioelectricity',
    'Biopreserv Biobank',
    'Biores Open Access',
    'Biosecur Bioterror',
    'Biotechnol Law Rep',
    'Brain Connect',
    'Breastfeed Med',
    'CRISPR J',
    'Cancer Biother',
    'Cancer Biother Radiopharm',
    'Cancer Drug Deliv',
    'Cannabis Cannabinoid Res',
    'Case Rep Pancreat Cancer',
    'Cell Preserv Technol',
    'Cell Reprogram',
    'Cent Nerv Syst Trauma',
    'Clin Thyroidol',
    'Cloning',
    'Cloning Stem Cells',
    'Cyberpsychol Behav',
    'Cyberpsychol Behav Soc Netw',
    'Diabetes Technol Ther',
    'Dis Manag',
    'Ecopsychology',
    'Elect Law J',
    'Environ Eng Sci',
    'Environ Justice',
    'Facial Plast Surg Aesthet Med',
    'Foodborne Pathog Dis',
    'Games Health J',
    'Gaming Law Rev Econ',
    'Genome Sci Technol',
    'Health Equity',
    'Health Secur',
    'High Alt Med Biol',
    'Hum Gene Ther',
    'Hum Gene Ther Clin Dev',
    'Hum Gene Ther Methods',
    'Hybrid Hybridomics',
    'Hybridoma',
    'Ind Biotechnol',
    'J Adolesc Young Adult Oncol',
    'J Aerosol Med',
    'J Aerosol Med Pulm Drug Deliv',
    'J Altern Complement Med',
    'J Anti Aging Med',
    'J Caffeine Adenosine Res',
    'J Caffeine Res',
    'J Child Adolesc Psychopharmacol',
    'J Clin Laser Med Surg',
    'J Comput Biol',
    'J Correct Health Care',
    'J Endourol B Videourol',
    'J Endourol Case Rep',
    'J Gynecol Surg',
    'J Hematother',
    'J Hematother Stem Cell Res',
    'J Interferon Cytokine Res',
    'J Interferon Res',
    'J Laparoendosc Adv Surg Tech A',
    'J Laparoendosc Adv Surg Tech Part B Videoscop',
    'J Laparoendosc Surg',
    'J Med Food',
    'J Neurotrauma',
    'J Ocul Pharmacol',
    'J Ocul Pharmacol Ther',
    'J Palliat Med',
    'J Pancreat Cancer',
    'J Womens Health',
    'J Womens Health Gend Based Med',
    'LGBT Health',
    'Lymphat Res Biol',
    'Med Acupunct',
    'Metab Syndr Relat Disord',
    'Microb Comp Genomics',
    'Microb Drug Resist',
    'Mol Urol',
    'Monoclon Antib Immunodiagn Immunother',
    'Netw Syst Med',
    'Neurotrauma Rep',
    'New Space',
    'Nucleic Acid Ther',
    'OMICS',
    'Obes Manag',
    'Obes Weight Manag',
    'Oligonucleotides',
    'Palliat Med Rep',
    'Pediatr Allergy Immunol Pulmonol',
    'Pediatr Asthma Allergy Immunol',
    'Phage',
    'Photobiomodul Photomed Laser Surg',
    'Photomed Laser Surg',
    'Popul Health Manag',
    'Rejuvenation Res',
    'Sel Cancer Ther',
    'Soft Robot',
    'Stem Cells Dev',
    'Surg Infect',
    'Syst Med',
    'Telemed J',
    'Telemed Rep',
    'Ther Hypothermia Temp Manag',
    'Tissue Eng',
    'Tissue Eng Part A',
    'Tissue Eng Part B Rev',
    'Tissue Eng Part C Methods',
    'Transgend Health',
    'VideoEndocrinology',
    'Videourology',
    'Violence Gend',
    'Viral Immunol',
    'Womens Health Rep',
    'Zebrafish',
]

# DOI template for Liebert journals
liebert_template = 'http://online.liebertpub.com/doi/pdf/{doi}'