"""MDPI (Multidisciplinary Digital Publishing Institute) journals.

MDPI journals use DOI pattern 10.3390/... and are primarily available through PMC.
This module provides backup PDF access for when PMC is unavailable.

URL pattern: https://www.mdpi.com/{ISSN}/{volume}/{issue}/{article}/pdf
"""

# Template for MDPI backup PDF URLs
# The URL should be the resolved DOI URL + '/pdf'
mdpi_template = '{url}/pdf'

# MDPI journals from unknown publishers analysis
# DOI pattern: 10.3390/...
mdpi_journals = [
    'Membranes',
    'Membranes (Basel)',
    'MPS', 
    'Environments',
    'DNA',
    'Life',
    'Antioxidants (Basel)',
    'Antibiotics (Basel)',
    'Nutrients',
    'Int J Mol Sci',
    'Molecules',
    'Sensors',
    'Materials',
    'Polymers',
    'Symmetry',
    'Entropy',
    'Water',
    'Sustainability',
    'Energies',
    'Remote Sens',
    'Atmosphere',
    'Climate',
    'Forests',
    'Land',
    'Fire',
    'Toxins',
    'Pathogens',
    'Viruses',
    'Microorganisms',
    'Genes',
    'Cells',
    'Biology',
    'Biomedicines',
    'Pharmaceutics',
    'Pharmacy',
    'Med Sci',
    'Diagnostics',
    'Healthcare',
    'Int J Environ Res Public Health',
    'Cancers',
    'Brain Sci',
    'Behav Sci',
    'Soc Sci',
    'Religions',
    'Laws',
    'Adm Sci',
    'Economies',
    'J Risk Financial Manag',
    'Mathematics',
    'Computation',
    'Algorithms',
    'Information',
    'Electronics',
    'Sensors',
    'Appl Sci',
    'Processes',
    'ChemEngineering',
    'Catalysts',
    'Nanomaterials',
    'Crystals',
    'Metals',
    'Coatings',
    'Lubricants',
    'Fluids',
    'Aerospace',
    'Robotics',
    'Actuators',
    'Machines',
    'Inventions',
    'Designs',
    'Arts',
    'Heritage',
    'Buildings',
    'Infrastructures',
    'Smart Cities',
    'Urban Sci',
    'Geosciences',
    'Minerals',
    'Mining',
    'J Mar Sci Eng',
    'Hydrology',
    'Soil Syst',
    'Plants',
    'Horticulturae',
    'Agronomy',
    'Agriculture',
    'Animals',
    'Vet Sci',
    'Dairy',
    'Foods',
    'Beverages',
    'Fermentation',
    'Cosmetics',
    'J Funct Biomater',
    'Bioengineering',
    'Biomimetics',
    'J Dev Biol',
    'J Pers Med',
    'J Clin Med',
    'Medicina',
    'Dent J',
    'Oral',
    'Vision',
    'Audiol Res',
    'Geriatrics',
    'Pediatr Rep',
    'Pharmacy',
    'Nurse Rep',
    'Nurs Rep',
    'Challenges',
    'Sustainability',
    'Future Internet',
    'Big Data Cogn Comput',
    'Data',
    'Stats',
    'Risks',
    'Games',
    'Sports',
    'J Funct Morphol Kinesiol',
    'Disabilities',
    'Merits',
    'Publications',
    'Encyclopedia',
]