from __future__ import absolute_import, unicode_literals

# vip = Volume-Issue-Page format
#       URLs that have the same format except for the host name
#
# TODO: early release format

vip_format = 'http://{host}/content/{a.volume}/{a.issue}/{a.first_page}.full.pdf'

vip_journals = {
    'Ann Clin Biochem': {'host': 'acb.sagepub.com'},
    'Am J Clin Pathol': {'host': 'ajcp.ascpjournals.org'},
    'Am J Hypertens': {'host': 'ajh.oxfordjournals.org'},
    'Am J Physiol Cell Physiol': {'host': 'ajpcell.physiology.org'},
    'Am J Physiol Endocrinol Metab': {'host': 'ajpendo.physiology.org'},
    'Am J Physiol Gastrointest Liver Physiol': {'host': 'ajpgi.physiology.org'},
    'Am J Physiol Heart Circ Physiol': {'host': 'ajpheart.physiology.org'},
    'Am J Physiol Lung Cell Mol Physiol': {'host': 'ajplung.physiology.org'},
    'Am J Physiol Regul Integr Comp Physiol': {'host': 'ajpregu.physiology.org'},
    'Am J Physiol Renal Physiol': {'host': 'ajprenal.physiology.org'},
    # TODO: the rest of physiology.org. see: http://www.the-aps.org/mm/Publications/Journals
    'Angiology': {'host': 'ang.sagepub.com'},
    'Ann Oncol': {'host': 'annonc.oxfordjournals.org'},
    # TODO: backup_url: pmid lookup strategy, e.g.
    # http://aac.asm.org/cgi/pmidlookup?view=long&pmid=7689822
    'Anticancer Res': {'host': 'ar.iiarjournals.org'},
    'Antimicrob Agents Chemother': {'host': 'aac.asm.org'},
    'Appl Environ Microbiol': {'host': 'aem.asm.org'},
    'Arterioscler Thromb Vasc Biol': {'host': 'atvb.ahajournals.org'},
    'Assessment': {'host': 'asm.sagepub.com'},
    'Brain': {'host': 'brain.oxfordjournals.org'},
    'Breast Cancer Res': {'host': 'breast-cancer-research.com'},
    'Br J Anaesth': {'host': 'bja.oxfordjournals.org'},
    'Cancer Discov': {'host': 'cancerdiscovery.aacrjournals.org'},
    'Cancer Epidemiol Biomarkers Prev': {'host': 'cebp.aacrjournals.org'},
    'Cancer Res': {'host': 'cancerres.aacrjournals.org'},
    # TODO: backup_url: pmid lookup strategy, e.g.
    # http://www.cfp.ca/cgi/pmidlookup?view=long&pmid=19282532
    'Can Fam Physician': {'host': 'www.cfp.ca'},
    'Carcinogenesis': {'host': 'carcin.oxfordjournals.org'},
    'Cardiovasc Res': {'host': 'cardiovascres.oxfordjournals.org'},
    'Circulation': {'host': 'circ.ahajournals.org'},
    'Circ Arrhythm Electrophysiol': {'host': 'circep.ahajournals.org'},
    'Circ Cardiovasc Genet': {'host': 'circgenetics.ahajournals.org'},
    'Circ Res': {'host': 'circres.ahajournals.org'},
    'Clin Appl Thromb Hemost': {'host': 'cat.sagepub.com'},
    'Clin Cancer Res': {'host': 'clincancerres.aacrjournals.org'},
    'Clin Chem': {'host': 'clinchem.org'},
    'Clin Infect Dis': {'host': 'cid.oxfordjournals.org'},
    'Clin Microbiol Rev': {'host': 'cmr.asm.org'},
    'Clin Pediatr': {'host': 'cpj.sagepub.com'},
    'Clin Pediatr (Phila)': {'host': 'cpj.sagepub.com'},
    'Clin Vaccine Immunol': {'host': 'cvi.asm.org'},
    'Diabetes': {'host': 'diabetes.diabetesjournals.org'},
    'Diabetes Care': {'host': 'care.diabetesjournals.org'},
    'Drug Metab Dispos': {'host': 'dmd.aspetjournals.org'},
    # TODO: backup_url: pmid lookup strategy,
    # http://emboj.embopress.org/cgi/pmidlookup?view=long&pmid=9501081
    'EMBO J': {'host': 'emboj.embopress.org'},
    'Endocr Relat Cancer': {'host': 'erc.endocrinology-journals.org'},  #TODO this is now https://erc.bioscientifica.com/
    'Environ Entomol': {'host': 'ee.oxfordjournals.org'},
    'Eukaryot Cell': {'host': 'ec.asm.org'},
    'Eur Heart J': {'host': 'eurheartj.oxfordjournals.org'},
    'Eur J Endocrinol': {'host': 'eje-online.org'},
    'Eur Respir J': {'host': 'erj.ersjournals.com'},
    'FASEB J': {'host': 'fasebj.org'},
    'FEMS Microbiol Lett': {'host': 'femsle.oxfordjournals.org'},
    'Genome Announc': {'host': 'genomea.asm.org'},
    'Genome Biol': {'host': 'genomebiology.com'},
    'Genome Res': {'host': 'genome.cshlp.org'},
    'Genes Dev': {'host': 'genesdev.cshlp.org'},
    'Haematologica': {'host': 'haematologica.org'},
    'Hum Mol Genet': {'host': 'hmg.oxfordjournals.org'},
    'Hum Reprod': {'host': 'humrep.oxfordjournals.org'},
    'Hypertension': {'host': 'hyper.ahajournals.org'},
    'Infect Immun': {'host': 'iai.asm.org'},
    'Invest Ophthalmol Vis Sci': {'host': 'www.iovs.org'},
    'IOVS': {'host': 'iovs.org'},
    # TODO: backup_url: pmid lookup strategy,
    # http://jah.sagepub.com/cgi/pmidlookup?view=long&pmid=20056814
    'J Aging Health': {'host': 'jah.sagepub.com'},
    'J Am Soc Nephrol': {'host': 'jasn.asnjournals.org'},
    'J Antimicrob Chemother': {'host': 'jac.oxfordjournals.org'},
    'J Appl Physiol': {'host': 'jap.physiology.org'},
    # TODO: backup_url: pmid lookup strategy,
    # http://jb.asm.org/cgi/pmidlookup?view=long&pmid=7683021
    'J Bacteriol': {'host': 'jb.asm.org'},
    # TODO backup_url: pmid lookup strategy, e.g.
    # http://www.jbc.org/cgi/pmidlookup?view=long&pmid=14722075
    'J Biol Chem': {'host': 'www.jbc.org'},
    'J Bone Joint Surg Am': {'host': 'jbjs.org'},
    'J Cell Biol': {'host': 'jcb.rupress.org'},
    'J Cell Sci': {'host': 'jcs.biologists.org'},
    'J Child Neurol': {'host': 'jcn.sagepub.com'},
    'J Clin Oncol': {'host': 'jco.ascopubs.org'},
    'J Dent Res': {'host': 'jdr.sagepub.com'},
    #'J Endocrinol': {'host': 'joe.endocrinology-journals.org'},   #moved
    #'J Mol Endocrinol': {'host': 'jme.endocrinology-journals.org'}, # moved to endo.py
    'J Exp Med': {'host': 'jem.rupress.org'},
    'J Gerontol A Biol Sci Med Sci': {'host': 'biomedgerontology.oxfordjournals.org'},
    'J Hum Lact': {'host': 'jhl.sagepub.com'},
    'J Immunol': {'host': 'jimmunol.org'},
    'J Infect Dis': {'host': 'jid.oxfordjournals.org'},
    'J Lipid Res': {'host': 'www.jlr.org'},
    'J Clin Microbiol': {'host': 'jcm.asm.org'},
    'J Natl Cancer Inst': {'host': 'jnci.oxfordjournals.org'},
    'J Neurophysiol': {'host': 'jb.physiology.org'},
    'J Neurosci': {'host': 'jneurosci.org'},
    # TODO:  backup_url: pmid lookup strategy,
    # http://jn.nutrition.org/cgi/pmidlookup?view=long&pmid=10736367
    'J Nutr': {'host': 'jn.nutrition.org'},
    'J Pharmacol Exp Ther': {'host': 'jpet.aspetjournals.org'},
    'J Rheumatol': {'host': 'www.jrheum.org'},
    'J Renin Angiotensin Aldosterone Syst': {'host': 'jra.sagepub.com'},
    'J Virol': {'host': 'jvi.asm.org'},
    'Lupus': {'host': 'lup.sagepub.com'},
    'MBio': {'host': 'mbio.asm.org'},
    'mSystems': {'host': 'msystems.asm.org'},
    'mSphere': {'host': 'msphere.asm.org'},
    'Microbiol Mol Biol Rev': {'host': 'mmbr.asm.org'},
    'Mol Biol Cell': {'host': 'molbiolcell.org'},
    'Mol Cell Biol': {'host': 'mcb.asm.org'},
    'Mol Canc Therapeut': {'host': 'mct.aacrjournals.org'},
    'Mol Cancer Ther': {'host': 'mct.aacrjournals.org'},
    'Mol Hum Reprod': {'host': 'molehr.oxfordjournals.org'},
    'Mol Pharmacol': {'host': 'molpharm.aspetjournals.org'},
    'Mutagenesis': {'host': 'mutage.oxfordjournals.org'},
    'Neurology': {'host': 'neurology.org'},
    'Nephrol Dial Transplant': {'host': 'ndt.oxfordjournals.org'},
    'Nucleic Acids Res': {'host': 'nar.oxfordjournals.org'},
    'Orphanet J Rare Dis': {'host': 'ojrd.com'},
    'Pediatrics': {'host': 'pediatrics.aappublications.org'},
    # TODO: backup_url: pmid lookup strategy, e.g.
    # http://physiolgenomics.physiology.org/cgi/pmidlookup?view=long&pmid=15252189
    'Physiology (Bethesda)': {'host': 'physiologyonline.physiology.org'},
    'Physiol Genomics': {'host': 'physiolgenomics.physiology.org'},
    'Physiol Rep': {'host': 'physreports.physiology.org'},
    'Physiol Rev': {'host': 'physrev.physiology.org'},
    # TODO:  backup_url: pmid lookup strategy, e.g.
    # http://www.plantcell.org/cgi/pmidlookup?view=long&pmid=9501112
    'Plant Cell': {'host': 'www.plantcell.org'},
    'Plant Cell Physiol': {'host': 'pcp.oxfordjournals.org'},
    'Proc Natl Acad Sci USA': {'host': 'pnas.org'},
    'Protein Eng': {'host': 'peds.oxfordjournals.org'},
    'Protein Eng Des Sel': {'host': 'peds.oxfordjournals.org'},
    'QJM': {'host': 'qjmed.oxfordjournals.org'},
    'Radiat Res': {'host': 'jrr.oxfordjournals.org'},
    'Rheumatology (Oxford)': {'host': 'rheumatology.oxfordjournals.org'},
    'Science': {'host': 'sciencemag.org'},
    'Stroke': {'host': 'stroke.ahajournals.org'},

    'Acupunct Med': {'host': 'aim.bmj.com'},
    'Arch Dis Child': {'host': 'adc.bmj.com'},
    'Arch Dis Child Fetal Neonatal Ed': {'host': 'fn.bmj.com'},
    'Arch Dis Child Educ Pract Ed': {'host': 'ep.bmj.com'},
    'Ann Rheum Dis': {'host': 'ard.bmj.com'},
    'BMJ Innov': {'host': 'innovations.bmj.com'},
    'BMJ Open': {'host': 'bmjopen.bmj.com'},
    'BMJ Open Diabetes Res Care': {'host': 'drc.bmj.com'},
    'BMJ Open Resp Res': {'host': 'bmjopenrespres.bmj.com'},
    'BMJ Open Sport Exerc Med': {'host': 'bmjopensem.bmj.com'},
    'BMJ Qual Saf': {'host': 'qualitysafety.bmj.com'},
    'BMJ Qual Improv Report': {'host': 'qir.bmj.com'},
    'BMJ STEL': {'host': 'stel.bmj.com'},
    'BMJ Support Palliat Care': {'host': 'spcare.bmj.com'},
    'BMC Ophthalmol': {'host': 'bjo.bmj.com'},
    'Br J Sports Med': {'host': 'bjsm.bmj.com'},
    'Drug Ther Bull': {'host': 'dtb.bmj.com'},
    'Emerg Med J': {'host': 'emj.bmj.com'},
    'End Life J': {'host': 'eolj.bmj.com'},
    'ESMO Open': {'host': 'esmoopen.bmj.com'},
    'Eur J Hosp Pharm': {'host': 'ejhp.bmj.com'},
    'Evid Based Mental Health': {'host': 'ebmh.bmj.com'},
    'Evid Based Med': {'host': 'ebm.bmj.com'},
    'Evid Based Nurs': {'host': 'ebn.bmj.com'},
    'Frontline Gastroenterol': {'host': 'fg.bmj.com'},
    'Gut': {'host': 'gut.bmj.com'},
    'Heart': {'host': 'heart.bmj.com'},
    'Heart Asia': {'host': 'heartasia.bmj.com'},
    'Inj Prev': {'host': 'injuryprevention.bmj.com'},
    'In Pract': {'host': 'inpractice.bmj.com'},
    'J Clin Pathol': {'host': 'jcp.bmj.com'},
    'J Epidemiol Community Health': {'host': 'jech.bmj.com'},
    'J Fam Plann Reprod Health Care': {'host': 'jfprhc.bmj.com'},
    'J Investig Med': {'host': 'jim.bmj.com'},
    'J ISAKOS': {'host': 'jisakos.bmj.com'},
    'J Med Ethics': {'host': 'jme.bmj.com'},
    'J Med Genet': {'host': 'jmg.bmj.com'},
    'J Neurol Neurosurg Psychiatry': {'host': 'jnnp.bmj.com'},
    'J Neurointerv Surg': {'host': 'jnis.bmj.com'},
    'J R Army Med Corps': {'host': 'jramc.bmj.com'}, # not in Entrez journal list but has citation pmid 7602561
    'Lupus Sci Med': {'host': 'lupus.bmj.com'},
    'Med Humanities': {'host': 'mh.bmj.com'},
    'Occup Environ Med': {'host': 'oem.bmj.com'},
    'Open Heart': {'host': 'openheart.bmj.com'},
    'Pract Neurol': {'host': 'pn.bmj.com'},
    'RMD Open': {'host': 'rmdopen.bmj.com'},
    'Sex Transm Infect': {'host': 'sti.bmj.com'},
    'Vet Rec': {'host': 'veterinaryrecord.bmj.com'},
    'Vet Rec Case Rep': {'host': 'vetrecordcasereports.bmj.com'},
    'Vet Rec Open': {'host': 'vetrecordopen.bmj.com'},
    'Tob Control': {'host': 'tobaccocontrol.bmj.com'},
    'Postgrad Med J': {'host': 'pmj.bmj.com'},
    'Thorax': {'host': 'thorax.bmj.com'},

    # Oxford Academic journals (1.0 confidence + manually approved)
    'Aesthet Surg J': {'host': 'asj.oxfordjournals.org'},
    'Aesthet Surg J Open Forum': {'host': 'asjopenforum.oxfordjournals.org'},  # manually approved
    'Afr Aff (Lond)': {'host': 'afraf.oxfordjournals.org'},
    'Age Ageing': {'host': 'ageing.oxfordjournals.org'},
    'Alcohol Alcohol': {'host': 'alcalc.oxfordjournals.org'},
    'Am J Epidemiol': {'host': 'aje.oxfordjournals.org'},
    'Am J Jurisprud': {'host': 'ajj.oxfordjournals.org'},
    'Am lit Hist': {'host': 'alh.oxfordjournals.org'},
    'Analysis': {'host': 'analysis.oxfordjournals.org'},
    'Ann Bot': {'host': 'aob.oxfordjournals.org'},
    'Ann Entomol Soc Am': {'host': 'aesa.oxfordjournals.org'},
    'Ann Work Expo Health': {'host': 'annhyg.oxfordjournals.org'},
    'Antib Ther': {'host': 'abt.oxfordjournals.org'},
    'AoB Plants': {'host': 'aobpla.oxfordjournals.org'},
    'Appl Linguist': {'host': 'applij.oxfordjournals.org'},
    'Art Hist': {'host': 'arthistory.oxfordjournals.org'},
    'BJR Case Rep': {'host': 'bjrcr.oxfordjournals.org'},  # manually approved
    'BJS Open': {'host': 'bjsopen.oxfordjournals.org'},
    'Bioinformatics': {'host': 'bioinformatics.oxfordjournals.org'},
    'Biol Methods Protoc': {'host': 'biomethods.oxfordjournals.org'},
    'Biol Reprod': {'host': 'biolreprod.oxfordjournals.org'},
    'Biometrika': {'host': 'biomet.oxfordjournals.org'},
    'Biosci Biotechnol Biochem': {'host': 'bbb.oxfordjournals.org'},
    'Bioscience': {'host': 'bioscience.oxfordjournals.org'},
    'Biostatistics': {'host': 'biostatistics.oxfordjournals.org'},
    'Br J Criminol': {'host': 'bjc.oxfordjournals.org'},
    'Br J Radiol': {'host': 'bjrbir.oxfordjournals.org'},  # manually approved (BIR section)
    'Br Med Bull': {'host': 'bmb.oxfordjournals.org'},
    'Brain Commun': {'host': 'braincomms.oxfordjournals.org'},
    'Brief Bioinform': {'host': 'bib.oxfordjournals.org'},
    'Brief Funct Genomics': {'host': 'bfg.oxfordjournals.org'},
    'Bull Chem Soc Jpn': {'host': 'bcsj.oxfordjournals.org'},
    'Burns Trauma': {'host': 'burnstrauma.oxfordjournals.org'},
    'Cambridge J Econ': {'host': 'cje.oxfordjournals.org'},
    'Cereb Cortex': {'host': 'cercor.oxfordjournals.org'},
    'Cereb Cortex Commun': {'host': 'cercorcomms.oxfordjournals.org'},  # manually approved
    'CESifo Econ Stud': {'host': 'cesifo.oxfordjournals.org'},
    'Chem Senses': {'host': 'chemse.oxfordjournals.org'},
    'Child Sch': {'host': 'cs.oxfordjournals.org'},
    'Clin Kidney J': {'host': 'ckj.oxfordjournals.org'},
    'Commun Cult Crit': {'host': 'ccc.oxfordjournals.org'},  # manually approved
    'Community Dev J': {'host': 'cdj.oxfordjournals.org'},
    'Comput J': {'host': 'comjnl.oxfordjournals.org'},
    'Conserv Physiol': {'host': 'conphys.oxfordjournals.org'},
    'Contrib Polit Econ': {'host': 'cpe.oxfordjournals.org'},
    'Crohns Colitis 360': {'host': 'crohnscolitis360.oxfordjournals.org'},
    'Curr Leg Probl': {'host': 'clp.oxfordjournals.org'},
    'Curr Zool': {'host': 'cz.oxfordjournals.org'},
    'Database': {'host': 'database.oxfordjournals.org'},
    'Econom J': {'host': 'ectj.oxfordjournals.org'},
    'Econ J (London)': {'host': 'ej.oxfordjournals.org'},
    'Econ Policy': {'host': 'economicpolicy.oxfordjournals.org'},
    'Engl Hist Rev': {'host': 'ehr.oxfordjournals.org'},
    'Environ Epigenet': {'host': 'eep.oxfordjournals.org'},
    'Epidemiol Rev': {'host': 'epirev.oxfordjournals.org'},
    'Eur Heart J Acute Cardiovasc Care': {'host': 'ehjacc.oxfordjournals.org'},  # manually approved
    'Eur Heart J Cardiovasc Imaging': {'host': 'ehjcimaging.oxfordjournals.org'},  # manually approved
    'Eur Heart J Cardiovasc Pharmacother': {'host': 'ehjcvp.oxfordjournals.org'},  # manually approved
    'Eur Heart J Case Rep': {'host': 'ehjcr.oxfordjournals.org'},  # manually approved
    'Eur Heart J Qual Care Clin Outcomes': {'host': 'ehjqcco.oxfordjournals.org'},  # manually approved
    'Eur J Cardiovasc Nurs': {'host': 'eurjcn.oxfordjournals.org'},
    'Eur J Orthod': {'host': 'ejo.oxfordjournals.org'},
    'Eur J Prev Cardiol': {'host': 'eurjpc.oxfordjournals.org'},
    'Eur J Public Health': {'host': 'eurpub.oxfordjournals.org'},
    'Eur Rev Econ Hist': {'host': 'ereh.oxfordjournals.org'},
    'Evol Lett': {'host': 'evlett.oxfordjournals.org'},
    'Evol Med Public Health': {'host': 'emph.oxfordjournals.org'},
    'FEMS Microbiol Ecol': {'host': 'femsec.oxfordjournals.org'},
    'FEMS Microbiol Rev': {'host': 'femsre.oxfordjournals.org'},
    'FEMS Yeast Res': {'host': 'femsyr.oxfordjournals.org'},
    'Forensic Sci Res': {'host': 'fsr.oxfordjournals.org'},
    'Fr Hist': {'host': 'fh.oxfordjournals.org'},
    'Fr Stud': {'host': 'fs.oxfordjournals.org'},
    'Gastroenterol Rep (Oxf)': {'host': 'gastro.oxfordjournals.org'},
    'Genetics': {'host': 'genetics.oxfordjournals.org'},
    'Genome Biol Evol': {'host': 'gbe.oxfordjournals.org'},
    'Geophys J Int': {'host': 'gji.oxfordjournals.org'},
    'Gerontologist': {'host': 'gerontologist.oxfordjournals.org'},
    'Gigascience': {'host': 'gigascience.oxfordjournals.org'},
    'Glycobiology': {'host': 'glycob.oxfordjournals.org'},
    'Health Policy Plan': {'host': 'heapol.oxfordjournals.org'},
    'Health Promot Int': {'host': 'heapro.oxfordjournals.org'},
    'Health Soc Work': {'host': 'hsw.oxfordjournals.org'},
    'Hist Workshop J': {'host': 'hwj.oxfordjournals.org'},  # manually approved
    'Holocaust Genocide Stud': {'host': 'hgs.oxfordjournals.org'},
    'Hortic Res': {'host': 'hr.oxfordjournals.org'},
    'Hum Commun Res': {'host': 'hcr.oxfordjournals.org'},
    'Hum Reprod Open': {'host': 'hropen.oxfordjournals.org'},
    'Hum Reprod Open': {'host': 'humrep.oxfordjournals.org'},  # manually approved (main journal)
    'Hum Reprod Update': {'host': 'humupd.oxfordjournals.org'},
    'IMA J Appl Math': {'host': 'imamat.oxfordjournals.org'},
    'IMA J Appl Math': {'host': 'imaman.oxfordjournals.org'},  # manually approved (management math)
    'Inf inference': {'host': 'imaiai.oxfordjournals.org'},  # manually approved
    'Innov Aging': {'host': 'innovateage.oxfordjournals.org'},
    'Insect Syst Divers': {'host': 'isd.oxfordjournals.org'},
    'In Silico Plants': {'host': 'insilicoplants.oxfordjournals.org'},
    'Integr Org Biol': {'host': 'iob.oxfordjournals.org'},
    'Integr Comp Biol': {'host': 'icb.oxfordjournals.org'},
    'Int Aff': {'host': 'ia.oxfordjournals.org'},
    'Int Health': {'host': 'inthealth.oxfordjournals.org'},
    'Int Immunol': {'host': 'intimm.oxfordjournals.org'},
    'Int J Const Law': {'host': 'icon.oxfordjournals.org'},
    'Int J Epidemiol': {'host': 'ije.oxfordjournals.org'},
    'Int J Law Policy Family': {'host': 'lawfam.oxfordjournals.org'},  # manually approved
    'Int J Neuropsychopharmacol': {'host': 'ijnp.oxfordjournals.org'},
    'Int J Pharm Pract': {'host': 'ijpp.oxfordjournals.org'},
    'Int J Public Opin Res': {'host': 'ijpor.oxfordjournals.org'},
    'Int J Transit Justice': {'host': 'ijtj.oxfordjournals.org'},
    'Int J Clin Endocrinol Metab': {'host': 'jcem.oxfordjournals.org'},  # manually approved
    'ISME J': {'host': 'ismej.oxfordjournals.org'},
    'JAC Antimicrob Resist': {'host': 'jacamr.oxfordjournals.org'},
    'JAMIA Open': {'host': 'jamiaopen.oxfordjournals.org'},
    'Jpn J Clin Oncol': {'host': 'jjco.oxfordjournals.org'},
    'J Afr Econ': {'host': 'jae.oxfordjournals.org'},
    'J Am Hist': {'host': 'jah.oxfordjournals.org'},
    'J Am Med Inform Assoc': {'host': 'jamia.oxfordjournals.org'},  # manually approved
    'J Anal Toxicol': {'host': 'jat.oxfordjournals.org'},
    'J Anim Sci': {'host': 'jas.oxfordjournals.org'},
    'J AOAC Int': {'host': 'jaoac.oxfordjournals.org'},
    'J Appl Lab Med': {'host': 'jalm.oxfordjournals.org'},
    'J Breast Imaging': {'host': 'jbi.oxfordjournals.org'},
    'J Can Assoc Gastroenterol': {'host': 'jcag.oxfordjournals.org'},
    'J Chromatogr Sci': {'host': 'chromsci.oxfordjournals.org'},
    'J Church State': {'host': 'jcs.oxfordjournals.org'},  # manually approved
    'J Commun': {'host': 'joc.oxfordjournals.org'},
    'J Comput Des Eng': {'host': 'jcde.oxfordjournals.org'},
    'J Comput Mediat Commun': {'host': 'jcmc.oxfordjournals.org'},  # manually approved
    'J Complex Netw': {'host': 'comnet.oxfordjournals.org'},
    'J Consum Res': {'host': 'jcr.oxfordjournals.org'},
    'J Deaf Stud Deaf Educ': {'host': 'jdsde.oxfordjournals.org'},
    'J Des Hist': {'host': 'jdh.oxfordjournals.org'},
    'J Endocr Soc': {'host': 'jes.oxfordjournals.org'},
    'J Eur Econ Assoc': {'host': 'jeea.oxfordjournals.org'},
    'J Exp Bot': {'host': 'jxb.oxfordjournals.org'},
    'J For': {'host': 'jof.oxfordjournals.org'},
    'J Gerontol': {'host': 'geronj.oxfordjournals.org'},
    'J Hered': {'host': 'jhered.oxfordjournals.org'},
    'J Hip Preserv Surg': {'host': 'jhps.oxfordjournals.org'},
    'J Hist Med Allied Sci': {'host': 'jhmas.oxfordjournals.org'},
    'J Hum Rights Pract': {'host': 'jhrp.oxfordjournals.org'},
    'J Insect Sci': {'host': 'jinsectscience.oxfordjournals.org'},
    'J Integr Pest Manag': {'host': 'jipm.oxfordjournals.org'},
    'J Lang Evol': {'host': 'jole.oxfordjournals.org'},
    'J Law Biosci': {'host': 'jlb.oxfordjournals.org'},
    'J Law Econ Organ': {'host': 'jleo.oxfordjournals.org'},
    'J Leukoc Biol': {'host': 'jleukbio.oxfordjournals.org'},
    'J Med Entomol': {'host': 'jme.oxfordjournals.org'},
    'J Mol Cell Biol': {'host': 'jmcb.oxfordjournals.org'},
    'J Molluscan Stud': {'host': 'mollus.oxfordjournals.org'},
    'J Music Ther': {'host': 'jmt.oxfordjournals.org'},
    'J Pediatr Psychol': {'host': 'jpepsy.oxfordjournals.org'},
    'J Pediatric Infect Dis Soc': {'host': 'jpids.oxfordjournals.org'},
    'J Plankton Res': {'host': 'plankt.oxfordjournals.org'},
    'J Plant Ecol': {'host': 'jpe.oxfordjournals.org'},  # manually approved
    'J Public Adm Res Theory': {'host': 'jpart.oxfordjournals.org'},  # manually approved
    'J Public Health (Oxf)': {'host': 'jpubhealth.oxfordjournals.org'},
    'J R Stat Soc Ser C Appl Stat': {'host': 'jrsssc.oxfordjournals.org'},  # manually approved
    'J Refug Stud': {'host': 'jrs.oxfordjournals.org'},
    'J Semant': {'host': 'jos.oxfordjournals.org'},
    'J Semit Stud': {'host': 'jss.oxfordjournals.org'},
    'J Soc Hist': {'host': 'jsh.oxfordjournals.org'},
    'J Surg Case Rep': {'host': 'jscr.oxfordjournals.org'},
    'J Surv Stat Methodol': {'host': 'jssam.oxfordjournals.org'},
    'J Travel Med': {'host': 'jtm.oxfordjournals.org'},
    'J Trop Pediatr (Lond)': {'host': 'tropej.oxfordjournals.org'},
    'J Vic Cult': {'host': 'jvc.oxfordjournals.org'},  # manually approved
    'JNCI Cancer Spectr': {'host': 'jncics.oxfordjournals.org'},
    'Library (Lond)': {'host': 'library.oxfordjournals.org'},
    'Log J IGPL': {'host': 'jigpal.oxfordjournals.org'},
    'Math Med Biol': {'host': 'imammb.oxfordjournals.org'},  # manually approved
    'Med Law Rev': {'host': 'medlaw.oxfordjournals.org'},
    'Med Mycol': {'host': 'mmy.oxfordjournals.org'},
    'Micros Today': {'host': 'mt.oxfordjournals.org'},
    'Microscopy (Oxf)': {'host': 'jmicro.oxfordjournals.org'},
    'Migr Stud': {'host': 'migration.oxfordjournals.org'},
    'Mod Rheumatol Case Rep': {'host': 'mrcr.oxfordjournals.org'},
    'Mol Biol Evol': {'host': 'mbe.oxfordjournals.org'},
    'Mon Not R Astron Soc': {'host': 'mnras.oxfordjournals.org'},
    'Mon Not R Astron Soc Lett': {'host': 'mnrasl.oxfordjournals.org'},  # manually approved
    'Music Lett': {'host': 'ml.oxfordjournals.org'},
    'Music Ther Perspect': {'host': 'mtp.oxfordjournals.org'},
    'NAR Cancer': {'host': 'narcancer.oxfordjournals.org'},
    'NAR Genom Bioinform': {'host': 'nargab.oxfordjournals.org'},
    'Natl Sci Rev': {'host': 'nsr.oxfordjournals.org'},
    'Neurooncol Adv': {'host': 'noa.oxfordjournals.org'},
    'Neurooncol Pract': {'host': 'nop.oxfordjournals.org'},
    'Neurosci Conscious': {'host': 'nc.oxfordjournals.org'},
    'Nucleic Acids Symp Ser (Oxf)': {'host': 'nass.oxfordjournals.org'},
    'Nutr Rev': {'host': 'nutritionreviews.oxfordjournals.org'},
    'Occup Med (Lond)': {'host': 'occmed.oxfordjournals.org'},
    'Oncologist': {'host': 'oncolo.oxfordjournals.org'},
    'Open Forum Infect Dis': {'host': 'ofid.oxfordjournals.org'},
    'Opera Q': {'host': 'oq.oxfordjournals.org'},
    'Oxf Econ Pap': {'host': 'oep.oxfordjournals.org'},
    'Oxf J Leg Stud': {'host': 'ojls.oxfordjournals.org'},
    'Oxf Med Case Reports': {'host': 'omcr.oxfordjournals.org'},
    'Oxf Open Immunol': {'host': 'ooim.oxfordjournals.org'},
    'Paediatr Child Health': {'host': 'pch.oxfordjournals.org'},
    'Parliam Aff': {'host': 'pa.oxfordjournals.org'},
    'Past Present': {'host': 'past.oxfordjournals.org'},
    'Pathog Dis': {'host': 'femspd.oxfordjournals.org'},
    'Perspect Public Manag Gov': {'host': 'ppmg.oxfordjournals.org'},
    'Philos Q': {'host': 'pq.oxfordjournals.org'},
    'Phys Ther': {'host': 'ptj.oxfordjournals.org'},
    'Plant Physiol': {'host': 'plphys.oxfordjournals.org'},
    'Polit Sci Q': {'host': 'psq.oxfordjournals.org'},
    'Precis Clin Med': {'host': 'pcm.oxfordjournals.org'},
    'Public Health Ethics': {'host': 'phe.oxfordjournals.org'},
    'Public Policy Aging Rep': {'host': 'ppar.oxfordjournals.org'},
    'Q J Econ': {'host': 'qje.oxfordjournals.org'},
    'Q J Mech Appl Math': {'host': 'qjmam.oxfordjournals.org'},
    'Radiat Prot Dosimetry': {'host': 'rpd.oxfordjournals.org'},
    'Regen Biomater': {'host': 'rb.oxfordjournals.org'},
    'Res Eval': {'host': 'rev.oxfordjournals.org'},
    'Rev Asset Pricing Stud': {'host': 'raps.oxfordjournals.org'},
    'Rev Econ Stud': {'host': 'restud.oxfordjournals.org'},
    'Rev Financ': {'host': 'rof.oxfordjournals.org'},
    'Rev Financ Stud': {'host': 'rfs.oxfordjournals.org'},
    'Rheumatol Adv Pract': {'host': 'rheumap.oxfordjournals.org'},
    'Rheumatology': {'host': 'rheumatology.oxfordjournals.org'},
    'Schizophr Bull': {'host': 'schizophreniabulletin.oxfordjournals.org'},
    'Schizophr Bull Open': {'host': 'schizbullopen.oxfordjournals.org'},
    'Sci Public Policy': {'host': 'spp.oxfordjournals.org'},
    'Screen (London)': {'host': 'screen.oxfordjournals.org'},
    'Sex Med': {'host': 'smoa.oxfordjournals.org'},
    'Sex Med Rev': {'host': 'smr.oxfordjournals.org'},
    'Signif (Oxf)': {'host': 'jrssig.oxfordjournals.org'},
    'Sleep': {'host': 'sleep.oxfordjournals.org'},
    'Soc Cogn Affect Neurosci': {'host': 'scan.oxfordjournals.org'},
    'Soc Work Res': {'host': 'swr.oxfordjournals.org'},
    'Soc Work Res Abstr': {'host': 'swra.oxfordjournals.org'},
    'Social Work (Stellenbosch)': {'host': 'sw.oxfordjournals.org'},
    'Socioecon Rev': {'host': 'ser.oxfordjournals.org'},
    'Sociol Relig': {'host': 'socrel.oxfordjournals.org'},
    'Stem Cells Transl Med': {'host': 'stcltm.oxfordjournals.org'},
    'Synth Biol (Oxf)': {'host': 'synbio.oxfordjournals.org'},
    'Syst Biol': {'host': 'sysbio.oxfordjournals.org'},
    'Toxicol Res (Camb)': {'host': 'toxres.oxfordjournals.org'},
    'Trans R Soc Trop Med Hyg': {'host': 'trstmh.oxfordjournals.org'},
    'Transl Anim Sci': {'host': 'tas.oxfordjournals.org'},
    'Transl Behav Med': {'host': 'tbm.oxfordjournals.org'},
    'Tree Physiol': {'host': 'treephys.oxfordjournals.org'},
    'Virus Evol': {'host': 've.oxfordjournals.org'},
    'Work Aging Retire': {'host': 'workar.oxfordjournals.org'},
    'World Bank Econ Rev': {'host': 'wber.oxfordjournals.org'},
    'World Bank Res Obs': {'host': 'wbro.oxfordjournals.org'},

    # Nature Publishing Group (current portfolio)
    'Acta Pharmacol Sin': {'host': 'nature.com'},
    'BDJ Open': {'host': 'nature.com'},
    'Biotechnology (N Y)': {'host': 'nature.com'},
    'Blood Cancer J': {'host': 'nature.com'},
    'Bone Marrow Transplant': {'host': 'nature.com'},
    'Bone Res': {'host': 'nature.com'},
    'Br Dent J': {'host': 'nature.com'},
    'Br J Cancer': {'host': 'nature.com'},
    'Cancer Gene Ther': {'host': 'nature.com'},
    'Cell Death Differ': {'host': 'nature.com'},
    'Cell Death Dis': {'host': 'nature.com'},
    'Cell Death Discov': {'host': 'nature.com'},
    'Cell Discov': {'host': 'nature.com'},
    'Cell Mol Immunol': {'host': 'nature.com'},
    'Cell Res': {'host': 'nature.com'},
    'Commun Biol': {'host': 'nature.com'},
    'Commun Chem': {'host': 'nature.com'},
    'Commun Earth Environ': {'host': 'nature.com'},
    'Commun Mater': {'host': 'nature.com'},
    'Commun Med': {'host': 'nature.com'},
    'Commun Phys': {'host': 'nature.com'},
    'Evid Based Dent': {'host': 'nature.com'},
    'Exp Mol Med': {'host': 'nature.com'},
    'Gene Ther': {'host': 'nature.com'},
    'Genetics': {'host': 'nature.com'},
    'Heredity (Edinb)': {'host': 'nature.com'},
    'Hum Genome Var': {'host': 'nature.com'},
    'Humanit Soc Sci Commun': {'host': 'nature.com'},
    'Immunology': {'host': 'nature.com'},
    'Int J Impot Res': {'host': 'nature.com'},
    'Int J Obes Suppl': {'host': 'nature.com'},
    'Int J Oral Sci': {'host': 'nature.com'},
    'J Antibiot (Tokyo)': {'host': 'nature.com'},
    'J Expo Anal Environ Epidemiol': {'host': 'nature.com'},
    'J Expo Sci Environ Epidemiol': {'host': 'nature.com'},
    'J Perinatol': {'host': 'nature.com'},
    'Jinrui Idengaku Zasshi': {'host': 'nature.com'},
    'Jpn J Hum Genet': {'host': 'nature.com'},
    'Lab Anim (NY)': {'host': 'nature.com'},
    'Leuk Suppl': {'host': 'nature.com'},
    'Light Sci Appl': {'host': 'nature.com'},
    'Microsyst Nanoeng': {'host': 'nature.com'},
    'NPG Asia Mater': {'host': 'nature.com'},
    'NPJ 2D Mater Appl': {'host': 'nature.com'},
    'NPJ Aging Mech Dis': {'host': 'nature.com'},
    'NPJ Biofilms Microbiomes': {'host': 'nature.com'},
    'NPJ Breast Cancer': {'host': 'nature.com'},
    'NPJ Clean Water': {'host': 'nature.com'},
    'NPJ Clim Atmos Sci': {'host': 'nature.com'},
    'NPJ Digit Med': {'host': 'nature.com'},
    'NPJ Genom Med': {'host': 'nature.com'},
    'NPJ Microgravity': {'host': 'nature.com'},
    'NPJ Parkinsons Dis': {'host': 'nature.com'},
    'NPJ Precis Oncol': {'host': 'nature.com'},
    'NPJ Prim Care Respir Med': {'host': 'nature.com'},
    'NPJ Quantum Mater': {'host': 'nature.com'},
    'NPJ Regen Med': {'host': 'nature.com'},
    'NPJ Schizophr': {'host': 'nature.com'},
    'NPJ Sci Food': {'host': 'nature.com'},
    'NPJ Sci Learn': {'host': 'nature.com'},
    'NPJ Syst Biol Appl': {'host': 'nature.com'},
    'NPJ Vaccines': {'host': 'nature.com'},
    'Nat Aging': {'host': 'nature.com'},
    'Nat Astron': {'host': 'nature.com'},
    'Nat Biomed Eng': {'host': 'nature.com'},
    'Nat Cancer': {'host': 'nature.com'},
    'Nat Catal': {'host': 'nature.com'},
    'Nat Chem Biol': {'host': 'nature.com'},
    'Nat Clim Chang': {'host': 'nature.com'},
    'Nat Ecol Evol': {'host': 'nature.com'},
    'Nat Electron': {'host': 'nature.com'},
    'Nat Energy': {'host': 'nature.com'},
    'Nat Food': {'host': 'nature.com'},
    'Nat Geosci': {'host': 'nature.com'},
    'Nat Hum Behav': {'host': 'nature.com'},
    'Nat Immunol': {'host': 'nature.com'},
    'Nat Mach Intell': {'host': 'nature.com'},
    'Nat Metab': {'host': 'nature.com'},
    'Nat Microbiol': {'host': 'nature.com'},
    'Nat New Biol': {'host': 'nature.com'},
    'Nat Photonics': {'host': 'nature.com'},
    'Nat Phys': {'host': 'nature.com'},
    'Nat Plants': {'host': 'nature.com'},
    'Nat Rep Stem Cells': {'host': 'nature.com'},
    'Nat Rev Cancer': {'host': 'nature.com'},
    'Nat Rev Chem': {'host': 'nature.com'},
    'Nat Rev Dis Primers': {'host': 'nature.com'},
    'Nat Rev Earth Environ': {'host': 'nature.com'},
    'Nat Rev Mater': {'host': 'nature.com'},
    'Nat Rev Microbiol': {'host': 'nature.com'},
    'Nat Rev Neurosci': {'host': 'nature.com'},
    'Nat Struct Biol': {'host': 'nature.com'},
    'Nat Struct Mol Biol': {'host': 'nature.com'},
    'Nat Sustain': {'host': 'nature.com'},
    'Nutr Diabetes': {'host': 'nature.com'},
    'Oncogenesis': {'host': 'nature.com'},
    'Palgrave Commun': {'host': 'nature.com'},
    'Paraplegia': {'host': 'nature.com'},
    'Polym J': {'host': 'nature.com'},
    'Prim Care Respir J': {'host': 'nature.com'},
    'Prostate Cancer Prostatic Dis': {'host': 'nature.com'},
    'Sci Data': {'host': 'nature.com'},
    'Sci Rep': {'host': 'nature.com'},
    'Signal Transduct Target Ther': {'host': 'nature.com'},
    'Spinal Cord': {'host': 'nature.com'},
    'Spinal Cord Ser Cases': {'host': 'nature.com'},
    'Transl Psychiatry': {'host': 'nature.com'},
    'Zhongguo Yao Li Xue Bao': {'host': 'nature.com'},
    'npj Quantum Inf': {'host': 'nature.com'},
}

# volume-issue-page type URLs but with a nonstandard baseurl construction.
# e.g. Blood: http://www.bloodjournal.org/content/bloodjournal/79/10/2507.full.pdf
#      BMJ:   http://www.bmj.com/content/bmj/350/bmj.h3317.full.pdf
# Thorax:
# http://thorax.bmj.com/content/early/2015/06/23/thoraxjnl-2015-207199.full.pdf+html

# no trailing slash in baseurl (please)
vip_journals_nonstandard = {
    # TODO: backup_url: pmid lookup strategy, e.g.
    # http://www.bloodjournal.org/cgi/pmidlookup?view=long&pmid=1586703
    'Blood': 'http://www.bloodjournal.org/content/bloodjournal/{a.volume}/{a.issue}/{a.first_page}.full.pdf',
    'BMJ':   'http://www.bmj.com/content/bmj/{a.volume}/bmj.{a.first_page}.full.pdf',
}

# Non-VIP, not sure where to put yet
# 'BMJ Case Rep': {'host': 'casereports.bmj.com', 'example': 'http://casereports.bmj.com/content/2016/bcr-2015-214310'}
#

