from __future__ import absolute_import, unicode_literals

# nature journals -- see http://www.nature.com/siteindex/index.html
nature_format = 'http://www.nature.com/{ja}/journal/v{a.volume}/n{a.issue}/pdf/{a.pii}.pdf'
nature_journals = {
    'Am J Gastroenterol': {'ja': 'ajg'},
    'Eur J Clin Nutr': {'ja': 'ejcn'},
    'Eur J Hum Genet': {'ja': 'ejhg'},
    'Eye (Lond)': {'ja': 'eye'},
    'Genes Immun': {'ja': 'gene'},
    'Genet Med': {'ja': 'gim'},
    'Hypertens Res': {'ja': 'hr'},
    'Int J Obes Relat Metab Disord': {'ja': 'ijo'},
    'Int J Obes (Lond)': {'ja': 'ijo'},
    'J Invest Dermatol': {'ja': 'jid'},
    'J Hum Genet': {'ja': 'jhg'},
    'J Hum Hypertens': {'ja': 'jhh'},
    'Kidney Int': {'ja': 'ki'},
    'Leukemia': {'ja': 'leu'},
    'Mod Pathol': {'ja': 'modpathol'},
    'Mol Psychiatry': {'ja': 'mp'},
    'Nature': {'ja': 'nature'},
    'Nat Biotechnol': {'ja': 'nbt'},
    'Nat Cell Biol': {'ja': 'ncb'},
    'Nat Chem': {'ja': 'nchem'},
    'Nat Clin Pract Endocrinol Metab': {'ja': 'nrendo'},
    'Nat Clin Pract Cardiovasc Med': {'ja': 'nrcardio'},
    'Nat Clin Pract Oncol': {'ja': 'nrclinonc'},
    'Nat Clin Pract Gastroenterol Hepatol': {'ja': 'nrgastro'},
    'Nat Clin Pract Urol': {'ja': 'nrurol'},
    'Nat Clin Pract Neurol': {'ja': 'nrneurol'},
    'Nat Clin Pract Nephrol': {'ja': 'nrneph'},
    'Nat Clin Pract Rheumatol': {'ja': 'nrrheum'},
    'Nat Genet': {'ja': 'ng'},
    'Nat Commun': {'ja': 'ncomms'},
    'Nat Nanotechnol': {'ja': 'nnano'},
    'Nat Neurosci': {'ja': 'neuro'},
    'Nat Mater': {'ja': 'nmat'},
    'Nat Med': {'ja': 'nm'},
    'Nat Methods': {'ja': 'nmeth'},
    'Nat Protoc': {'ja': 'nprot'},
    'Nat Rev Drug Discov': {'ja': 'nrd'},
    'Nat Rev Cardiol': {'ja': 'nrcardio'},
    'Nat Rev Clin Oncol': {'ja': 'nrclinonc'},
    'Nat Rev Endocrinol': {'ja': 'nrendo'},
    'Nat Rev Genet': {'ja': 'nrg'},
    'Nat Rev Gastroenterol Hepatol': {'ja': 'nrgastro'},
    'Nat Rev Mol Cell Biol': {'ja': 'nrm'},
    'Nat Rev Nephrol': {'ja': 'nrneph'},
    'Nat Rev Neurol': {'ja': 'nrneurol'},
    'Nat Rev Rheumatol': {'ja': 'nrrheum'},
    'Nat Rev Urol': {'ja': 'nrurol'},
    'Nat Rev Immunol': {'ja': 'nri'},
    'Neuropsychopharmacology': {'ja': 'npp'},
    'Oncogene': {'ja': 'onc'},
    'Pediatr Res': {'ja': 'pr'},
    'Pharmacogenomics J': {'ja': 'tpj'},
    # Additional Nature journals found in PMID data
    ## BELOW ARE UNTESTED, SOME PROBABLY WRONG -- HANG TIGHT
    'Nat Rev Microbiol': {'ja': 'nrmicro'},
    'Nat Immunol': {'ja': 'ni'},
    'Cell Mol Immunol': {'ja': 'cmi'},
    'Nat Rev Cancer': {'ja': 'nrc'},
    'Nat Ecol Evol': {'ja': 's41559'},
    'Nat Hum Behav': {'ja': 's41562'},
    'Nat Rev Dis Primers': {'ja': 'nrdp'},
    'Nat Rev Chem': {'ja': 's41570'},
    'Nat Struct Mol Biol': {'ja': 'nsmb'},
    'Nat Food': {'ja': 's43016'},
    'Nat Metab': {'ja': 's42255'},
    'Nat Cancer': {'ja': 's43018'},
    'Nat Chem Biol': {'ja': 'nchembio'},
    'Nat Rev Neurosci': {'ja': 'nrn'},
    'Nat Aging': {'ja': 's43587'},
    'Nat Plants': {'ja': 'nplants'},
    'Nat Biomed Eng': {'ja': 's41551'},
    'Nat Struct Biol': {'ja': 'nsb'},  # Legacy name for Nat Struct Mol Biol
    'Nat New Biol': {'ja': 'newbio'},  # Legacy Nature journal
    'Paraplegia': {'ja': 'sc'},  # Now Spinal Cord
    'Spinal Cord': {'ja': 'sc'},
    # Non-Nature publisher journals that appear in Nature PMIDs
    'Biotechnology (N Y)': {'ja': 'nbt'},  # Actually Nature Biotechnology variation
    'Int J Impot Res': {'ja': 'ijir'},
    'J Antibiot (Tokyo)': {'ja': 'ja'},
    'J Expo Anal Environ Epidemiol': {'ja': 'jea'},
    'J Expo Sci Environ Epidemiol': {'ja': 'jes'},
    'Bone Marrow Transplant': {'ja': 'bmt'},
    'Acta Pharmacol Sin': {'ja': 'aps'},
    'Jpn J Hum Genet': {'ja': 'jhg'},
    'Lab Anim (NY)': {'ja': 'laban'},
    'Evid Based Dent': {'ja': 'ebd'},
    'Cell Death Differ': {'ja': 'cdd'},
    'Gene Ther': {'ja': 'gt'},
    'J Perinatol': {'ja': 'jp'},
    'Jinrui Idengaku Zasshi': {'ja': 'jhg'},  # Japanese name for J Hum Genet
    'Br Dent J': {'ja': 'bdj'},
    'Prostate Cancer Prostatic Dis': {'ja': 'pcan'},
    ## END UNTESTED / UNRELIABLE SECTION
}
