"""
Oxford University Press journal patterns and mappings.

Oxford University Press publishes over 270 academic journals using VIP 
(Volume-Issue-Page) format URLs hosted on oxfordjournals.org.

URL Pattern: http://{host}/content/{volume}/{issue}/{first_page}.full.pdf
Dance Function: the_vip_shake (VIP format)
"""

# Publisher metadata
PUBLISHER_INFO = {
    'name': 'Oxford University Press',
    'dance_function': 'the_vip_shake',
    'base_url': 'https://academic.oup.com',
    'url_pattern': 'http://{host}/content/{volume}/{issue}/{first_page}.full.pdf',
    'identifier_type': 'vip'  # Volume-Issue-Page format
}

# Oxford journals are available as keys in oxford_journal_params dictionary

# Host mappings for Oxford journals (extracted from misc_vip.py)
oxford_journal_params = {
    'Am J Hypertens': {'host': 'ajh.oxfordjournals.org'},
    'Ann Oncol': {'host': 'annonc.oxfordjournals.org'},
    'Brain': {'host': 'brain.oxfordjournals.org'},
    'Br J Anaesth': {'host': 'bja.oxfordjournals.org'},
    'Carcinogenesis': {'host': 'carcin.oxfordjournals.org'},
    'Cardiovasc Res': {'host': 'cardiovascres.oxfordjournals.org'},
    'Clin Infect Dis': {'host': 'cid.oxfordjournals.org'},
    'Environ Entomol': {'host': 'ee.oxfordjournals.org'},
    'Eur Heart J': {'host': 'eurheartj.oxfordjournals.org'},
    'FEMS Microbiol Lett': {'host': 'femsle.oxfordjournals.org'},
    'Hum Mol Genet': {'host': 'hmg.oxfordjournals.org'},
    'Hum Reprod': {'host': 'humrep.oxfordjournals.org'},
    'J Antimicrob Chemother': {'host': 'jac.oxfordjournals.org'},
    'J Gerontol A Biol Sci Med Sci': {'host': 'biomedgerontology.oxfordjournals.org'},
    'J Infect Dis': {'host': 'jid.oxfordjournals.org'},
    'J Natl Cancer Inst': {'host': 'jnci.oxfordjournals.org'},
    'Mol Hum Reprod': {'host': 'molehr.oxfordjournals.org'},
    'Mutagenesis': {'host': 'mutage.oxfordjournals.org'},
    'Nephrol Dial Transplant': {'host': 'ndt.oxfordjournals.org'},
    'Nucleic Acids Res': {'host': 'nar.oxfordjournals.org'},
    'Plant Cell Physiol': {'host': 'pcp.oxfordjournals.org'},
    'Protein Eng': {'host': 'peds.oxfordjournals.org'},
    'Protein Eng Des Sel': {'host': 'peds.oxfordjournals.org'},
    'QJM': {'host': 'qjmed.oxfordjournals.org'},
    'Radiat Res': {'host': 'jrr.oxfordjournals.org'},
    'Rheumatology (Oxford)': {'host': 'rheumatology.oxfordjournals.org'},
    'Aesthet Surg J': {'host': 'asj.oxfordjournals.org'},
    'Aesthet Surg J Open Forum': {'host': 'asjopenforum.oxfordjournals.org'},
    'Afr Aff (Lond)': {'host': 'afraf.oxfordjournals.org'},
    'Age Ageing': {'host': 'ageing.oxfordjournals.org'},
    'Alcohol Alcohol': {'host': 'alcalc.oxfordjournals.org'},
    'Am J Epidemiol': {'host': 'aje.oxfordjournals.org'},
    'Am J Jurisprud': {'host': 'ajj.oxfordjournals.org'},
    'Am lit Hist': {'host': 'alh.oxfordjournals.org'},
    'Analysis': {'host': 'analysis.oxfordjournals.org'},
    'Ann Bot': {'host': 'aob.oxfordjournals.org'},
    'Ann Entomol Soc Am': {'host': 'aesa.oxfordjournals.org'},
    'Ann Work Expo Health': {'host': 'annhyg.oxfordjournals.org'},
    'Antib Ther': {'host': 'abt.oxfordjournals.org'},
    'AoB Plants': {'host': 'aobpla.oxfordjournals.org'},
    'Appl Linguist': {'host': 'applij.oxfordjournals.org'},
    'Art Hist': {'host': 'arthistory.oxfordjournals.org'},
    'BJR Case Rep': {'host': 'bjrcr.oxfordjournals.org'},
    'BJS Open': {'host': 'bjsopen.oxfordjournals.org'},
    'Bioinformatics': {'host': 'bioinformatics.oxfordjournals.org'},
    'Biol Methods Protoc': {'host': 'biomethods.oxfordjournals.org'},
    'Biol Reprod': {'host': 'biolreprod.oxfordjournals.org'},
    'Biometrika': {'host': 'biomet.oxfordjournals.org'},
    'Biosci Biotechnol Biochem': {'host': 'bbb.oxfordjournals.org'},
    'Bioscience': {'host': 'bioscience.oxfordjournals.org'},
    'Biostatistics': {'host': 'biostatistics.oxfordjournals.org'},
    'Br J Criminol': {'host': 'bjc.oxfordjournals.org'},
    'Br J Radiol': {'host': 'bjrbir.oxfordjournals.org'},
    'Br Med Bull': {'host': 'bmb.oxfordjournals.org'},
    'Brain Commun': {'host': 'braincomms.oxfordjournals.org'},
    'Brief Bioinform': {'host': 'bib.oxfordjournals.org'},
    'Brief Funct Genomics': {'host': 'bfg.oxfordjournals.org'},
    'Bull Chem Soc Jpn': {'host': 'bcsj.oxfordjournals.org'},
    'Burns Trauma': {'host': 'burnstrauma.oxfordjournals.org'},
    'Cambridge J Econ': {'host': 'cje.oxfordjournals.org'},
    'Cereb Cortex': {'host': 'cercor.oxfordjournals.org'},
    'Cereb Cortex Commun': {'host': 'cercorcomms.oxfordjournals.org'},
    'CESifo Econ Stud': {'host': 'cesifo.oxfordjournals.org'},
    'Chem Senses': {'host': 'chemse.oxfordjournals.org'},
    'Child Sch': {'host': 'cs.oxfordjournals.org'},
    'Clin Kidney J': {'host': 'ckj.oxfordjournals.org'},
    'Commun Cult Crit': {'host': 'ccc.oxfordjournals.org'},
    'Community Dev J': {'host': 'cdj.oxfordjournals.org'},
    'Comput J': {'host': 'comjnl.oxfordjournals.org'},
    'Conserv Physiol': {'host': 'conphys.oxfordjournals.org'},
    'Contrib Polit Econ': {'host': 'cpe.oxfordjournals.org'},
    'Crohns Colitis 360': {'host': 'crohnscolitis360.oxfordjournals.org'},
    'Curr Leg Probl': {'host': 'clp.oxfordjournals.org'},
    'Curr Zool': {'host': 'cz.oxfordjournals.org'},
    'Database': {'host': 'database.oxfordjournals.org'},
    'Econom J': {'host': 'ectj.oxfordjournals.org'},
    'Econ J (London)': {'host': 'ej.oxfordjournals.org'},
    'Econ Policy': {'host': 'economicpolicy.oxfordjournals.org'},
    'Engl Hist Rev': {'host': 'ehr.oxfordjournals.org'},
    'Environ Epigenet': {'host': 'eep.oxfordjournals.org'},
    'Epidemiol Rev': {'host': 'epirev.oxfordjournals.org'},
    'Eur Heart J Acute Cardiovasc Care': {'host': 'ehjacc.oxfordjournals.org'},
    'Eur Heart J Cardiovasc Imaging': {'host': 'ehjcimaging.oxfordjournals.org'},
    'Eur Heart J Cardiovasc Pharmacother': {'host': 'ehjcvp.oxfordjournals.org'},
    'Eur Heart J Case Rep': {'host': 'ehjcr.oxfordjournals.org'},
    'Eur Heart J Qual Care Clin Outcomes': {'host': 'ehjqcco.oxfordjournals.org'},
    'Eur J Cardiovasc Nurs': {'host': 'eurjcn.oxfordjournals.org'},
    'Eur J Orthod': {'host': 'ejo.oxfordjournals.org'},
    'Eur J Prev Cardiol': {'host': 'eurjpc.oxfordjournals.org'},
    'Eur J Public Health': {'host': 'eurpub.oxfordjournals.org'},
    'Eur Rev Econ Hist': {'host': 'ereh.oxfordjournals.org'},
    'Evol Lett': {'host': 'evlett.oxfordjournals.org'},
    'Evol Med Public Health': {'host': 'emph.oxfordjournals.org'},
    'FEMS Microbiol Ecol': {'host': 'femsec.oxfordjournals.org'},
    'FEMS Microbiol Rev': {'host': 'femsre.oxfordjournals.org'},
    'FEMS Yeast Res': {'host': 'femsyr.oxfordjournals.org'},
    'Forensic Sci Res': {'host': 'fsr.oxfordjournals.org'},
    'Fr Hist': {'host': 'fh.oxfordjournals.org'},
    'Fr Stud': {'host': 'fs.oxfordjournals.org'},
    'Gastroenterol Rep (Oxf)': {'host': 'gastro.oxfordjournals.org'},
    'Genetics': {'host': 'genetics.oxfordjournals.org'},
    'Genome Biol Evol': {'host': 'gbe.oxfordjournals.org'},
    'Geophys J Int': {'host': 'gji.oxfordjournals.org'},
    'Gerontologist': {'host': 'gerontologist.oxfordjournals.org'},
    'Gigascience': {'host': 'gigascience.oxfordjournals.org'},
    'Glycobiology': {'host': 'glycob.oxfordjournals.org'},
    'Health Policy Plan': {'host': 'heapol.oxfordjournals.org'},
    'Health Promot Int': {'host': 'heapro.oxfordjournals.org'},
    'Health Soc Work': {'host': 'hsw.oxfordjournals.org'},
    'Hist Workshop J': {'host': 'hwj.oxfordjournals.org'},
    'Holocaust Genocide Stud': {'host': 'hgs.oxfordjournals.org'},
    'Hortic Res': {'host': 'hr.oxfordjournals.org'},
    'Hum Commun Res': {'host': 'hcr.oxfordjournals.org'},
    'Hum Reprod Open': {'host': 'hropen.oxfordjournals.org'},
    'Hum Reprod Update': {'host': 'humupd.oxfordjournals.org'},
    'IMA J Appl Math': {'host': 'imamat.oxfordjournals.org'},
    'Inf inference': {'host': 'imaiai.oxfordjournals.org'},
    'Innov Aging': {'host': 'innovateage.oxfordjournals.org'},
    'Insect Syst Divers': {'host': 'isd.oxfordjournals.org'},
    'In Silico Plants': {'host': 'insilicoplants.oxfordjournals.org'},
    'Integr Org Biol': {'host': 'iob.oxfordjournals.org'},
    'Integr Comp Biol': {'host': 'icb.oxfordjournals.org'},
    'Int Aff': {'host': 'ia.oxfordjournals.org'},
    'Int Health': {'host': 'inthealth.oxfordjournals.org'},
    'Int Immunol': {'host': 'intimm.oxfordjournals.org'},
    'Int J Const Law': {'host': 'icon.oxfordjournals.org'},
    'Int J Epidemiol': {'host': 'ije.oxfordjournals.org'},
    'Int J Law Policy Family': {'host': 'lawfam.oxfordjournals.org'},
    'Int J Neuropsychopharmacol': {'host': 'ijnp.oxfordjournals.org'},
    'Int J Pharm Pract': {'host': 'ijpp.oxfordjournals.org'},
    'Int J Public Opin Res': {'host': 'ijpor.oxfordjournals.org'},
    'Int J Transit Justice': {'host': 'ijtj.oxfordjournals.org'},
    'Int J Clin Endocrinol Metab': {'host': 'jcem.oxfordjournals.org'},
    'ISME J': {'host': 'ismej.oxfordjournals.org'},
    'JAC Antimicrob Resist': {'host': 'jacamr.oxfordjournals.org'},
    'JAMIA Open': {'host': 'jamiaopen.oxfordjournals.org'},
    'Jpn J Clin Oncol': {'host': 'jjco.oxfordjournals.org'},
    'J Afr Econ': {'host': 'jae.oxfordjournals.org'},
    'J Am Hist': {'host': 'jah.oxfordjournals.org'},
    'J Am Med Inform Assoc': {'host': 'jamia.oxfordjournals.org'},
    'J Anal Toxicol': {'host': 'jat.oxfordjournals.org'},
    'J Anim Sci': {'host': 'jas.oxfordjournals.org'},
    'J AOAC Int': {'host': 'jaoac.oxfordjournals.org'},
    'J Appl Lab Med': {'host': 'jalm.oxfordjournals.org'},
    'J Breast Imaging': {'host': 'jbi.oxfordjournals.org'},
    'J Can Assoc Gastroenterol': {'host': 'jcag.oxfordjournals.org'},
    'J Chromatogr Sci': {'host': 'chromsci.oxfordjournals.org'},
    'J Church State': {'host': 'jcs.oxfordjournals.org'},
    'J Commun': {'host': 'joc.oxfordjournals.org'},
    'J Comput Des Eng': {'host': 'jcde.oxfordjournals.org'},
    'J Comput Mediat Commun': {'host': 'jcmc.oxfordjournals.org'},
    'J Complex Netw': {'host': 'comnet.oxfordjournals.org'},
    'J Consum Res': {'host': 'jcr.oxfordjournals.org'},
    'J Deaf Stud Deaf Educ': {'host': 'jdsde.oxfordjournals.org'},
    'J Des Hist': {'host': 'jdh.oxfordjournals.org'},
    'J Endocr Soc': {'host': 'jes.oxfordjournals.org'},
    'J Eur Econ Assoc': {'host': 'jeea.oxfordjournals.org'},
    'J Exp Bot': {'host': 'jxb.oxfordjournals.org'},
    'J For': {'host': 'jof.oxfordjournals.org'},
    'J Gerontol': {'host': 'geronj.oxfordjournals.org'},
    'J Hered': {'host': 'jhered.oxfordjournals.org'},
    'J Hip Preserv Surg': {'host': 'jhps.oxfordjournals.org'},
    'J Hist Med Allied Sci': {'host': 'jhmas.oxfordjournals.org'},
    'J Hum Rights Pract': {'host': 'jhrp.oxfordjournals.org'},
    'J Insect Sci': {'host': 'jinsectscience.oxfordjournals.org'},
    'J Integr Pest Manag': {'host': 'jipm.oxfordjournals.org'},
    'J Lang Evol': {'host': 'jole.oxfordjournals.org'},
    'J Law Biosci': {'host': 'jlb.oxfordjournals.org'},
    'J Law Econ Organ': {'host': 'jleo.oxfordjournals.org'},
    'J Leukoc Biol': {'host': 'jleukbio.oxfordjournals.org'},
    'J Med Entomol': {'host': 'jme.oxfordjournals.org'},
    'J Mol Cell Biol': {'host': 'jmcb.oxfordjournals.org'},
    'J Molluscan Stud': {'host': 'mollus.oxfordjournals.org'},
    'J Music Ther': {'host': 'jmt.oxfordjournals.org'},
    'J Pediatr Psychol': {'host': 'jpepsy.oxfordjournals.org'},
    'J Pediatric Infect Dis Soc': {'host': 'jpids.oxfordjournals.org'},
    'J Plankton Res': {'host': 'plankt.oxfordjournals.org'},
    'J Plant Ecol': {'host': 'jpe.oxfordjournals.org'},
    'J Public Adm Res Theory': {'host': 'jpart.oxfordjournals.org'},
    'J Public Health (Oxf)': {'host': 'jpubhealth.oxfordjournals.org'},
    'J R Stat Soc Ser C Appl Stat': {'host': 'jrsssc.oxfordjournals.org'},
    'J Refug Stud': {'host': 'jrs.oxfordjournals.org'},
    'J Semant': {'host': 'jos.oxfordjournals.org'},
    'J Semit Stud': {'host': 'jss.oxfordjournals.org'},
    'J Soc Hist': {'host': 'jsh.oxfordjournals.org'},
    'J Surg Case Rep': {'host': 'jscr.oxfordjournals.org'},
    'J Surv Stat Methodol': {'host': 'jssam.oxfordjournals.org'},
    'J Travel Med': {'host': 'jtm.oxfordjournals.org'},
    'J Trop Pediatr (Lond)': {'host': 'tropej.oxfordjournals.org'},
    'J Vic Cult': {'host': 'jvc.oxfordjournals.org'},
    'JNCI Cancer Spectr': {'host': 'jncics.oxfordjournals.org'},
    'Library (Lond)': {'host': 'library.oxfordjournals.org'},
    'Log J IGPL': {'host': 'jigpal.oxfordjournals.org'},
    'Math Med Biol': {'host': 'imammb.oxfordjournals.org'},
    'Med Law Rev': {'host': 'medlaw.oxfordjournals.org'},
    'Med Mycol': {'host': 'mmy.oxfordjournals.org'},
    'Micros Today': {'host': 'mt.oxfordjournals.org'},
    'Microscopy (Oxf)': {'host': 'jmicro.oxfordjournals.org'},
    'Migr Stud': {'host': 'migration.oxfordjournals.org'},
    'Mod Rheumatol Case Rep': {'host': 'mrcr.oxfordjournals.org'},
    'Mol Biol Evol': {'host': 'mbe.oxfordjournals.org'},
    'Mon Not R Astron Soc': {'host': 'mnras.oxfordjournals.org'},
    'Mon Not R Astron Soc Lett': {'host': 'mnrasl.oxfordjournals.org'},
    'Music Lett': {'host': 'ml.oxfordjournals.org'},
    'Music Ther Perspect': {'host': 'mtp.oxfordjournals.org'},
    'NAR Cancer': {'host': 'narcancer.oxfordjournals.org'},
    'NAR Genom Bioinform': {'host': 'nargab.oxfordjournals.org'},
    'Natl Sci Rev': {'host': 'nsr.oxfordjournals.org'},
    'Neurooncol Adv': {'host': 'noa.oxfordjournals.org'},
    'Neurooncol Pract': {'host': 'nop.oxfordjournals.org'},
    'Neurosci Conscious': {'host': 'nc.oxfordjournals.org'},
    'Nucleic Acids Symp Ser (Oxf)': {'host': 'nass.oxfordjournals.org'},
    'Nutr Rev': {'host': 'nutritionreviews.oxfordjournals.org'},
    'Occup Med (Lond)': {'host': 'occmed.oxfordjournals.org'},
    'Oncologist': {'host': 'oncolo.oxfordjournals.org'},
    'Open Forum Infect Dis': {'host': 'ofid.oxfordjournals.org'},
    'Opera Q': {'host': 'oq.oxfordjournals.org'},
    'Oxf Econ Pap': {'host': 'oep.oxfordjournals.org'},
    'Oxf J Leg Stud': {'host': 'ojls.oxfordjournals.org'},
    'Oxf Med Case Reports': {'host': 'omcr.oxfordjournals.org'},
    'Oxf Open Immunol': {'host': 'ooim.oxfordjournals.org'},
    'Paediatr Child Health': {'host': 'pch.oxfordjournals.org'},
    'Parliam Aff': {'host': 'pa.oxfordjournals.org'},
    'Past Present': {'host': 'past.oxfordjournals.org'},
    'Pathog Dis': {'host': 'femspd.oxfordjournals.org'},
    'Perspect Public Manag Gov': {'host': 'ppmg.oxfordjournals.org'},
    'Philos Q': {'host': 'pq.oxfordjournals.org'},
    'Phys Ther': {'host': 'ptj.oxfordjournals.org'},
    'Plant Physiol': {'host': 'plphys.oxfordjournals.org'},
    'Polit Sci Q': {'host': 'psq.oxfordjournals.org'},
    'Precis Clin Med': {'host': 'pcm.oxfordjournals.org'},
    'Public Health Ethics': {'host': 'phe.oxfordjournals.org'},
    'Public Policy Aging Rep': {'host': 'ppar.oxfordjournals.org'},
    'Q J Econ': {'host': 'qje.oxfordjournals.org'},
    'Q J Mech Appl Math': {'host': 'qjmam.oxfordjournals.org'},
    'Radiat Prot Dosimetry': {'host': 'rpd.oxfordjournals.org'},
    'Regen Biomater': {'host': 'rb.oxfordjournals.org'},
    'Res Eval': {'host': 'rev.oxfordjournals.org'},
    'Rev Asset Pricing Stud': {'host': 'raps.oxfordjournals.org'},
    'Rev Econ Stud': {'host': 'restud.oxfordjournals.org'},
    'Rev Financ': {'host': 'rof.oxfordjournals.org'},
    'Rev Financ Stud': {'host': 'rfs.oxfordjournals.org'},
    'Rheumatol Adv Pract': {'host': 'rheumap.oxfordjournals.org'},
    'Rheumatology': {'host': 'rheumatology.oxfordjournals.org'},
    'Schizophr Bull': {'host': 'schizophreniabulletin.oxfordjournals.org'},
    'Schizophr Bull Open': {'host': 'schizbullopen.oxfordjournals.org'},
    'Sci Public Policy': {'host': 'spp.oxfordjournals.org'},
    'Screen (London)': {'host': 'screen.oxfordjournals.org'},
    'Sex Med': {'host': 'smoa.oxfordjournals.org'},
    'Sex Med Rev': {'host': 'smr.oxfordjournals.org'},
    'Signif (Oxf)': {'host': 'jrssig.oxfordjournals.org'},
    'Sleep': {'host': 'sleep.oxfordjournals.org'},
    'Soc Cogn Affect Neurosci': {'host': 'scan.oxfordjournals.org'},
    'Soc Work Res': {'host': 'swr.oxfordjournals.org'},
    'Soc Work Res Abstr': {'host': 'swra.oxfordjournals.org'},
    'Social Work (Stellenbosch)': {'host': 'sw.oxfordjournals.org'},
    'Socioecon Rev': {'host': 'ser.oxfordjournals.org'},
    'Sociol Relig': {'host': 'socrel.oxfordjournals.org'},
    'Stem Cells Transl Med': {'host': 'stcltm.oxfordjournals.org'},
    'Synth Biol (Oxf)': {'host': 'synbio.oxfordjournals.org'},
    'Syst Biol': {'host': 'sysbio.oxfordjournals.org'},
    'Toxicol Res (Camb)': {'host': 'toxres.oxfordjournals.org'},
    'Trans R Soc Trop Med Hyg': {'host': 'trstmh.oxfordjournals.org'},
    'Transl Anim Sci': {'host': 'tas.oxfordjournals.org'},
    'Transl Behav Med': {'host': 'tbm.oxfordjournals.org'},
    'Tree Physiol': {'host': 'treephys.oxfordjournals.org'},
    'Virus Evol': {'host': 've.oxfordjournals.org'},
    'Work Aging Retire': {'host': 'workar.oxfordjournals.org'},
    'World Bank Econ Rev': {'host': 'wber.oxfordjournals.org'},
    'World Bank Res Obs': {'host': 'wbro.oxfordjournals.org'},
}

# VIP URL template for Oxford journals
oxford_vip_template = 'http://{host}/content/{volume}/{issue}/{first_page}.full.pdf'