sciencedirect_url = 'http://www.sciencedirect.com/science/article/pii/{piit}'

sciencedirect_journals = [
        'Acad Pediatr',
        'Acta Astronaut',
        'Acta Biomater',
        'Acta Cardiol',
        'Acta Histochem',
        'Acta Reumatol Port',
        'Acta Trop',
        'Actas Dermosifiliogr',
        'Actas Urol Esp',
        'Adv Biophys',
        'Adv Cancer Res',
        'Adv Clin Chem',
        'Adv Colloid Interface Sci',
        'Adv Drug Deliv Rev',
        'Adv Enzyme Regul',
        'Adv Med Sci',
        'Adv Protein Chem',
        'Adv Virus Res',
        'Ageing Res Rev',
        'Air Med J',
        'Alcohol',
        'Allergol Immunopathol (Madr)',
        'Allergol Int',
        'Alzheimers Dement',
        'Am J Emerg Med',
        'Am J Geriatr Psychiatry',
        'Am J Kidney Dis',
        'Am J Obstet Gynecol',
        'Am J Orthod Dentofacial Orthop',
        'Am J Otolaryngol',
        'Am J Pathol',
        'Am J Prev Med',
        'Am J Surg',
        'Ambul Pediatr',
        'An Pediatr (Barc)',
        'Anal Biochem',
        'Anal Chim Acta',
        'Anim Reprod Sci',
        'Ann Acad Med Singap',
        'Ann Allergy Asthma Immunol',
        'Ann Chir Gynaecol',
        'Ann Diagn Pathol',
        'Ann Emerg Med',
        'Ann Endocrinol (Paris)',
        'Ann Epidemiol',
        'Ann Genet',
        'Ann Hepatol',
        'Ann Inst Pasteur Immunol',
        'Ann Inst Pasteur Microbiol',
        'Ann Intern Med',
        'Ann Pathol',
        'Ann Thorac Surg',
        'Ann Transplant',
        'Ann Vasc Surg',
        'Antivir Ther (Lond)',
        'Antiviral Res',
        'Appetite',
        'Appl Radiat Isot',
        'Aquat Toxicol',
        'Arch Biochem Biophys',
        'Arch Bronconeumol',
        'Arch Cardiovasc Dis',
        'Arch Gerontol Geriatr',
        'Arch Gerontol Geriatr Suppl',
        'Arch Med Res',
        'Arch Oral Biol',
        'Arch Pediatr',
        'Arch Soc Esp Oftalmol',
        'Arthroscopy',
        'Asian J Psychiatr',
        'Asian J Surg',
        'Asian Pac J Trop Med',
        'Aten Primaria',
        'Atheroscler Suppl',
        'Atherosclerosis',
        'Auris Nasus Larynx',
        'Aust J Physiother',
        'Autoimmun Rev',
        'Auton Neurosci',
        'Behav Brain Res',
        'Behav Neural Biol',
        'Behav Processes',
        'Beijing Da Xue Xue Bao',
        'Best Pract Res Clin Gastroenterol',
        'Best Pract Res Clin Haematol',
        'Best Pract Res Clin Rheumatol',
        'BioSystems',
        'Biochem Biophys Res Commun',
        'Biochem Med',
        'Biochem Med Metab Biol',
        'Biochem Mol Med',
        'Biochem Pharmacol',
        'Biochim Biophys Acta',
        'Biochimie',
        'Bioelectrochem Bioenerg',
        'Bioelectrochemistry',
        'Bioinorg Chem',
        'Biol Blood Marrow Transplant',
        'Biol Psychol',
        'Biologicals',
        'Biomaterials',
        'Biomed Environ Sci',
        'Biomed Pharmacother',
        'Biomol Eng',
        'Bioorg Chem',
        'Bioorg Med Chem',
        'Bioorg Med Chem Lett',
        'Biophys Chem',
        'Bioresour Technol',
        'Biosens Bioelectron',
        'Biotechnol Adv',
        'Blood Cells Mol Dis',
        'Blood Rev',
        'Bone Miner',
        'Br J Oral Maxillofac Surg',
        'Br J Plast Surg',
        'Br Vet J',
        'Brain Behav Immun',
        'Brain Cogn',
        'Brain Res',
        'Brain Res Brain Res Protoc',
        'Brain Res Brain Res Rev',
        'Brain Res Bull',
        'Brain Res Dev Brain Res',
        'Brain Res Gene Expr Patterns',
        'Brain Res Mol Brain Res',
        'Brain Stimul',
        'Braz J Anesthesiol',
        'Braz J Infect Dis',
        'Braz J Otorhinolaryngol',
        'Breast',
        'Bull Cancer',
        'Burns',
        'C R Acad Sci III, Sci Vie',
        'C R Biol',
        'Can J Cardiol',
        'Can J Diabetes',
        'Can J Ophthalmol',
        'Cancer Detect Prev',
        'Cancer Epidemiol',
        'Cancer Genet',
        'Cancer Radiother',
        'Cancer Treat Rev',
        'Carbohydr Polym',
        'Carbohydr Res',
        'Cardiovasc Pathol',
        'Cardiovasc Surg',
        'Cas Lek Cesk',
        'Cell Calcium',
        'Cell Differ Dev',
        'Cell Immunol',
        'Cell Rep',
        'Cell Signal',
        'Chem Biol Interact',
        'Chem Phys',
        'Chem Phys Lett',
        'Chem Phys Lipids',
        'Chemosphere',
        'Child Abuse Negl',
        'Child Adolesc Psychiatr Clin N Am',
        'Chin J Nat Med',
        'Chin Med J',
        'Chin Med Sci J',
        'Clin Biochem',
        'Clin Biomech (Bristol, Avon)',
        'Clin Breast Cancer',
        'Clin Chim Acta',
        'Clin Colorectal Cancer',
        'Clin Exp Rheumatol',
        'Clin Gastroenterol Hepatol',
        'Clin Genitourin Cancer',
        'Clin Immunol',
        'Clin Immunol Immunopathol',
        'Clin Investig Arterioscler',
        'Clin Lab Med',
        'Clin Lab Sci',
        'Clin Lung Cancer',
        'Clin Lymphoma Myeloma',
        'Clin Lymphoma Myeloma Leuk',
        'Clin Microbiol Infect',
        'Clin Neurophysiol',
        'Clin Nutr',
        'Clin Oncol (R Coll Radiol)',
        'Clin Psychol Rev',
        'Clin Res Hepatol Gastroenterol',
        'Clin Ther',
        'Colloids Surf B Biointerfaces',
        'Comp Biochem Physiol, B',
        'Comp Biochem Physiol B, Biochem Mol Biol',
        'Comp Biochem Physiol C, Pharmacol Toxicol Endocrinol',
        'Comp Biochem Physiol C Toxicol Pharmacol',
        'Comp Biochem Physiol, Part A Mol Integr Physiol',
        'Comp Biochem Physiol Part D Genomics Proteomics',
        'Comp Immunol Microbiol Infect Dis',
        'Compr Psychiatry',
        'Comput Biol Chem',
        'Comput Biol Med',
        'Comput Chem',
        'Comput Methods Programs Biomed',
        'Comput Radiol',
        'Cont Lens Anterior Eye',
        'Contemp Clin Trials',
        'Contraception',
        'Cortex',
        'Crit Care Clin',
        'Crit Rev Oncol Hematol',
        'Curr Opin Biotechnol',
        'Curr Opin Chem Biol',
        'Curr Opin Gastroenterol',
        'Curr Opin Genet Dev',
        'Curr Opin Plant Biol',
        'Curr Opin Struct Biol',
        'Curr Opin Virol',
        'Curr Probl Pediatr',
        'Cytokine',
        'Cytokine Growth Factor Rev',
        'Cytotherapy',
        'DNA Repair (Amst)',
        'Dent Mater',
        'Dev Biol',
        'Dev Comp Immunol',
        'Development',
        'Diabetes Metab',
        'Diabetes Metab Syndr',
        'Diagn Microbiol Infect Dis',
        'Dig Liver Dis',
        'Domest Anim Endocrinol',
        'Drug Alcohol Depend',
        'Drug Resist Updat',
        'Early Hum Dev',
        'Ecotoxicol Environ Saf',
        'Electroencephalogr Clin Neurophysiol',
        'Encephale',
        'Endocrinol Metab Clin North Am',
        'Endocrinol Nutr',
        'Enferm Infecc Microbiol Clin',
        'Environ Int',
        'Environ Pollut',
        'Environ Res',
        'Environ Toxicol Pharmacol',
        'Enzyme Microb Technol',
        'Epilepsy Behav',
        'Eur Ann Otorhinolaryngol Head Neck Dis',
        'Eur J Cancer',
        'Eur J Cancer Clin Oncol',
        'Eur J Cell Biol',
        'Eur J Gynaecol Oncol',
        'Eur J Intern Med',
        'Eur J Med Chem',
        'Eur J Med Genet',
        'Eur J Obstet Gynecol Reprod Biol',
        'Eur J Pharm Biopharm',
        'Eur J Pharm Sci',
        'Eur J Pharmacol',
        'Eur J Radiol',
        'Eur J Surg Oncol',
        'Eur J Ultrasound',
        'Eur J Vasc Endovasc Surg',
        'Eur Neuropsychopharmacol',
        'Eur Psychiatry',
        'Eur Urol',
        'Exp Cell Res',
        'Exp Eye Res',
        'Exp Gerontol',
        'Exp Mol Pathol',
        'Exp Neurol',
        'Exp Parasitol',
        'Exp Pathol (Jena)',
        'Exp Toxicol Pathol',
        'FEBS Lett',
        'Fam Pract',
        'Farm Hosp',
        'Farmaco',
        'Fish Shellfish Immunol',
        'Fitoterapia',
        'Fold Des',
        'Food Chem',
        'Food Chem Toxicol',
        'Food Microbiol',
        'Forensic Sci Int',
        'Forensic Sci Int Genet',
        'Free Radic Biol Med',
        'Fundam Appl Toxicol',
        'Fungal Biol',
        'Fungal Genet Biol',
        'Gac Sanit',
        'Gait Posture',
        'Gastroenterol Clin Biol',
        'Gastroenterol Clin North Am',
        'Gastroenterol Hepatol',
        'Gastrointest Endosc',
        'Gen Comp Endocrinol',
        'Gen Pharmacol',
        'Gend Med',
        'Gene',
        'Gene Expr Patterns',
        'Genet Anal',
        'Genet Anal Tech Appl',
        'Genomics',
        'Genomics Proteomics Bioinformatics',
        'Growth Horm IGF Res',
        'Gynecol Obstet Fertil',
        'HBPD INT',
        'Handb Clin Neurol',
        'Health Policy',
        'Hear Res',
        'Heart Lung',
        'Heart Lung Circ',
        'Hematol Oncol Clin North Am',
        'Hematol Oncol Stem Cell Ther',
        'Hepatol Res',
        'Homeopathy',
        'Homo',
        'Horm Behav',
        'Hum Immunol',
        'Hum Pathol',
        'Icarus',
        'Immunobiology',
        'Immunochemistry',
        'Immunol Lett',
        'Immunol Today',
        'Immunomethods',
        'Immunopharmacology',
        'Immunotechnology',
        'Infect Genet Evol',
        'Injury',
        'Insect Biochem Mol Biol',
        'Int Angiol',
        'Int Immunopharmacol',
        'Int J Antimicrob Agents',
        'Int J Biochem',
        'Int J Biochem Cell Biol',
        'Int J Biol Macromol',
        'Int J Dev Neurosci',
        'Int J Food Microbiol',
        'Int J Gynaecol Obstet',
        'Int J Hyg Environ Health',
        'Int J Immunopharmacol',
        'Int J Infect Dis',
        'Int J Med Microbiol',
        'Int J Obstet Anesth',
        'Int J Oral Maxillofac Surg',
        'Int J Parasitol',
        'Int J Pediatr Otorhinolaryngol',
        'Int J Pharm',
        'Int J Psychophysiol',
        'Int J Rad Appl Instrum A',
        'Int J Rad Appl Instrum B',
        'Int J Radiat Oncol Biol Phys',
        'Int Rev Cytol',
        'Int Rev Neurobiol',
        'J AAPOS',
        'J Acad Nutr Diet',
        'J Acupunct Meridian Stud',
        'J Adolesc',
        'J Adolesc Health',
        'J Affect Disord',
        'J Allergy Clin Immunol',
        'J Allergy Clin Immunol Pract',
        'J Am Acad Child Adolesc Psychiatry',
        'J Am Acad Dermatol',
        'J Am Coll Cardiol',
        'J Am Coll Surg',
        'J Am Dent Assoc',
        'J Am Diet Assoc',
        'J Am Soc Echocardiogr',
        'J Antibiot',
        'J Arthroplasty',
        'J Autoimmun',
        'J Auton Nerv Syst',
        'J Biochem Biophys Methods',
        'J Biomech',
        'J Biosci Bioeng',
        'J Biotechnol',
        'J Card Fail',
        'J Cardiol',
        'J Cardiothorac Vasc Anesth',
        'J Cataract Refract Surg',
        'J Chem Neuroanat',
        'J Chin Med Assoc',
        'J Chromatogr',
        'J Chromatogr A',
        'J Chromatogr B Analyt Technol Biomed Life Sci',
        'J Chromatogr B, Biomed Appl',
        'J Chromatogr B Biomed Sci Appl',
        'J Clin Anesth',
        'J Clin Densitom',
        'J Clin Epidemiol',
        'J Clin Gastroenterol',
        'J Clin Lipidol',
        'J Clin Neurosci',
        'J Clin Psychopharmacol',
        'J Clin Virol',
        'J Colloid Interface Sci',
        'J Comp Pathol',
        'J Contam Hydrol',
        'J Control Release',
        'J Craniomaxillofac Surg',
        'J Cyst Fibros',
        'J Dairy Res',
        'J Dairy Sci',
        'J Dent',
        'J Dermatol Sci',
        'J Diabetes Complicat',
        'J Egypt Natl Canc Inst',
        'J Electrocardiol',
        'J Emerg Med',
        'J Endod',
        'J Environ Manage',
        'J Environ Sci (China)',
        'J Ethnopharmacol',
        'J Foot Ankle Surg',
        'J Formos Med Assoc',
        'J Fr Ophtalmol',
        'J Genet Genomics',
        'J Gynecol Obstet Biol Reprod (Paris)',
        'J Hand Ther',
        'J Hazard Mater',
        'J Health Econ',
        'J Heart Lung Transplant',
        'J Hepatol',
        'J Hosp Infect',
        'J Hum Evol',
        'J Immunol Methods',
        'J Infect',
        'J Infect Chemother',
        'J Inorg Biochem',
        'J Insect Physiol',
        'J Invertebr Pathol',
        'J Invest Dermatol',
        'J Lab Clin Med',
        'J Magn Reson',
        'J Magn Reson B',
        'J Mal Vasc',
        'J Mech Behav Biomed Mater',
        'J Mechanochem Cell Motil',
        'J Med Dent Sci',
        'J Microbiol Immunol Infect',
        'J Microbiol Methods',
        'J Minim Invasive Gynecol',
        'J Mol Biol',
        'J Mol Graph Model',
        'J Mol Spectrosc',
        'J Mycol Med',
        'J Neuroimmunol',
        'J Neurol Sci',
        'J Neurosci Methods',
        'J Nurse Midwifery',
        'J Nutr Biochem',
        'J Oral Maxillofac Surg',
        'J Pain',
        'J Pediatr',
        'J Pediatr Health Care',
        'J Pediatr Surg',
        'J Pharm Biomed Anal',
        'J Pharmacol Sci',
        'J Pharmacol Toxicol Methods',
        'J Photochem Photobiol B, Biol',
        'J Plant Physiol',
        'J Prosthet Dent',
        'J Prosthodont Res',
        'J Protein Chem',
        'J Proteomics',
        'J Psychiatr Res',
        'J Psychosom Res',
        'J Radiat Res',
        'J Ren Nutr',
        'J Reprod Immunol',
        'J Sci Med Sport',
        'J Shoulder Elbow Surg',
        'J Soc Gynecol Investig',
        'J Steroid Biochem',
        'J Steroid Biochem Mol Biol',
        'J Stroke Cerebrovasc Dis',
        'J Struct Biol',
        'J Surg Res',
        'J Theor Biol',
        'J Thorac Cardiovasc Surg',
        'J Trace Elem Med Biol',
        'J Tradit Chin Med',
        'J Urol',
        'J Vasc Surg',
        'J Vet Cardiol',
        'J Virol Methods',
        'JACC Cardiovasc Imaging',
        'JACC Cardiovasc Interv',
        'Joint Bone Spine',
        'Jpn J Ophthalmol',
        'Kaohsiung J Med Sci',
        'Klin Oczna',
        'Knee',
        'Lab Invest',
        'Leg Med (Tokyo)',
        'Leuk Res',
        'Life Sci',
        'Liver Transpl Surg',
        'Lung Cancer',
        'MAGMA',
        'Magn Reson Imaging',
        'Mar Environ Res',
        'Mar Pollut Bull',
        'Mater Sci Eng C Mater Biol Appl',
        'Math Biosci',
        'Matrix',
        'Matrix Biol',
        'Maturitas',
        'Mayo Clin Proc',
        'Meat Sci',
        'Mech Ageing Dev',
        'Mech Dev',
        'Med Dosim',
        'Med Mal Infect',
        'Medicina (Kaunas)',
        'Metab Eng',
        'Meth Enzymol',
        'Methods',
        'Methods Mol Med',
        'Microb Pathog',
        'Microbes Infect',
        'Microbiol Res',
        'Microvasc Res',
        'Mikrobiyol Bul',
        'Mitochondrion',
        'Mol Aspects Med',
        'Mol Biochem Parasitol',
        'Mol Cell Biol Res Commun',
        'Mol Cell Endocrinol',
        'Mol Cell Neurosci',
        'Mol Cell Probes',
        'Mol Diagn',
        'Mol Gen Genet',
        'Mol Genet Metab',
        'Mol Immunol',
        'Mol Oncol',
        'Mol Phylogenet Evol',
        'Mol Plant',
        'Mult Scler Relat Disord',
        'Mutat Res',
        'Mutat Res Genet Toxicol Environ Mutagen',
        'Mutat Res Rev Mutat Res',
        'Mycol Res',
        'N Biotechnol',
        'Nanomedicine',
        'Nephrol Ther',
        'Neth J Med',
        'Neural Netw',
        'Neurobiol Dis',
        'Neurobiol Learn Mem',
        'Neurochem Int',
        'Neurochirurgie',
        'Neuroimage',
        'Neurol Neurochir Pol',
        'Neurologia',
        'Neuromuscul Disord',
        'Neuropeptides',
        'Neuropharmacology',
        'Neuropsychologia',
        'Neurosci Biobehav Rev',
        'Neurosci Lett',
        'Neurosci Res',
        'Neuroscience',
        'Neurotoxicol Teratol',
        'Neurotoxicology',
        'Nippon Rinsho',
        'Nitric Oxide',
        'Nucl Med Biol',
        'Nucleic Acids Res Suppl',
        'Nutr Hosp',
        'Nutr Metab Cardiovasc Dis',
        'Nutr Res',
        'Nutrition',
        'Obes Res Clin Pract',
        'Oral Oncol',
        'Oral Surg Oral Med Oral Pathol',
        'Oral Surg Oral Med Oral Pathol Oral Radiol',
        'Oral Surg Oral Med Oral Pathol Oral Radiol Endod',
        'Orthop Traumatol Surg Res',
        'Osteoarthr Cartil',
        'Otolaryngol Pol',
        'Paediatr Respir Rev',
        'Pancreas',
        'Pancreatology',
        'Parasitol Int',
        'Parkinsonism Relat Disord',
        'Pathol Biol',
        'Pathol Res Pract',
        'Pathophysiology',
        'Patient Educ Couns',
        'Pediatr Neonatol',
        'Pediatr Nurs',
        'Pediatr Pulmonol',
        'Peptides',
        'Pestic Biochem Physiol',
        'Pharmacol Biochem Behav',
        'Pharmacol Res',
        'Pharmacol Ther',
        'Photodiagnosis Photodyn Ther',
        'Phys Med',
        'Phys Rev, D',
        'Physiol Behav',
        'Phytochemistry',
        'Phytomedicine',
        'Plant Physiol Biochem',
        'Plant Sci',
        'Plasmid',
        'Postepy Hig Med Dosw (Online)',
        'Pract Radiat Oncol',
        'Pregnancy Hypertens',
        'Presse Med',
        'Prev Med',
        'Prev Vet Med',
        'Prog Biophys Mol Biol',
        'Prog Brain Res',
        'Prog Neuropsychopharmacol Biol Psychiatry',
        'Prog Nucleic Acid Res Mol Biol',
        'Prog Orthod',
        'Prostaglandins',
        'Prostaglandins Leukot Essent Fatty Acids',
        'Prostaglandins Leukot Med',
        'Prostaglandins Other Lipid Mediat',
        'Protein Expr Purif',
        'Protist',
        'Prz Lek',
        'Psychiatry Res',
        'Psychoneuroendocrinology',
        'Pulm Pharmacol',
        'Radiat Meas',
        'Radiat Med',
        'Radiother Oncol',
        'Regul Pept',
        'Regul Toxicol Pharmacol',
        'Reprod Biol',
        'Reprod Biomed Online',
        'Reprod Toxicol',
        'Res Dev Disabil',
        'Res Microbiol',
        'Res Vet Sci',
        'Res Virol',
        'Respir Investig',
        'Respir Med',
        'Respir Physiol',
        'Respir Physiol Neurobiol',
        'Resuscitation',
        'Reumatol Clin',
        'Rev Argent Microbiol',
        'Rev Bras Anestesiol',
        'Rev Bras Reumatol',
        'Rev Clin Esp',
        'Rev Epidemiol Sante Publique',
        'Rev Esp Cardiol (Engl Ed)',
        'Rev Iberoam Micol',
        'Rev Mal Respir',
        'Rev Med Inst Mex Seguro Soc',
        'Rev Med Interne',
        'Rev Neurol',
        'Rev Neurol (Paris)',
        'Rev Pneumol Clin',
        'Rev Psiquiatr Salud Ment',
        'Ross Fiziol Zh Im I M Sechenova',
        'Sci Total Environ',
        'Seizure',
        'Semin Arthritis Rheum',
        'Semin Cancer Biol',
        'Semin Cell Biol',
        'Semin Cell Dev Biol',
        'Semin Diagn Pathol',
        'Semin Fetal Neonatal Med',
        'Semin Hematol',
        'Semin Nephrol',
        'Semin Oncol',
        'Semin Pediatr Neurol',
        'Semin Perinatol',
        'Semin Vasc Surg',
        'Sheng Wu Gong Cheng Xue Bao',
        'Sleep Med',
        'Sleep Med Rev',
        'Soc Sci Med',
        'Solid State Nucl Magn Reson',
        'Spectrochim Acta A Mol Biomol Spectrosc',
        'Spine J',
        'Steroids',
        'Suppl Clin Neurophysiol',
        'Surg Obes Relat Dis',
        'Surg Oncol',
        'Surgery',
        'Surv Ophthalmol',
        'Syst Appl Microbiol',
        'Taiwan J Obstet Gynecol',
        'Talanta',
        'Tetrahedron Lett',
        'Theriogenology',
        'Toxicol Appl Pharmacol',
        'Toxicol In Vitro',
        'Toxicol Lett',
        'Toxicol Sci',
        'Toxicology',
        'Toxicon',
        'Transfus Apher Sci',
        'Transfus Clin Biol',
        'Transl Res',
        'Transpl Immunol',
        'Transplant Proc',
        'Travel Med Infect Dis',
        'Trends Biochem Sci',
        'Trends Cardiovasc Med',
        'Trends Endocrinol Metab',
        'Trends Genet',
        'Trends Immunol',
        'Trends Microbiol',
        'Trends Neurosci',
        'Trends Parasitol',
        'Tuber Lung Dis',
        'Tuberculosis (Edinb)',
        'Ultramicroscopy',
        'Ultrason Sonochem',
        'Ultrasonics',
        'Ultrasound Med Biol',
        'Urol Oncol',
        'Urology',
        'Vaccine',
        'Vasc Med',
        'Vascul Pharmacol',
        'Vet Immunol Immunopathol',
        'Vet J',
        'Vet Microbiol',
        'Vet Parasitol',
        'Virology',
        'Virus Res',
        'Vision Res',
        'Vitam Horm',
        'Waste Manag',
        'Water Res',
        'Wei Sheng Yan Jiu',
        'Wilderness Environ Med',
        'Yi Chuan',
        'Yi Chuan Xue Bao',
        'Zentralbl Bakteriol',
        'Zh Nevrol Psikhiatr Im S S Korsakova',
        'Zhonghua Fu Chan Ke Za Zhi',
        'Zhonghua Yan Ke Za Zhi',
        'Zhonghua Yi Xue Za Zhi',
]
