from __future__ import absolute_import, unicode_literals

# SCIRP (Scientific Research Publishing)
# Domain: scirp.org
# 
# SCIRP is an open access publisher founded in 2007, publishing over 230 journals
# across various academic disciplines including medicine, engineering, and social sciences.
# 
# Examples:
# PMID: 27213116 (Surg Sci) - Surgery Science journal
# PMID: 25019034 (J Sens Technol) - Journal of Sensor Technology
# PMID: 23837132 (World J Neurosci) - World Journal of Neuroscience
#
# URL Pattern: articles typically accessible via DOI resolution to scirp.org

scirp_journals = (
    'AQ',
    'Adv Aging Res',
    'Adv Alzheimer Dis',
    'Adv Appl Sociol',
    'Adv Biol Chem',
    'Adv Biosci Biotechnol',
    'Adv Breast Cancer Res',
    'Adv Enzyme Res',
    'Adv Infect Dis',
    'Adv J Mol Imaging',
    'Adv Lung Cancer',
    'Adv Microbiol',
    'Adv Nanopart',
    'Am J Analyt Chem',
    'Am J Clim Change',
    'Am J Mol Biol',
    'Am J Philol',
    'Am J Plant Sci',
    'Am Q',
    'Am Stud',
    'Appl Math',
    'Biography',
    'Bull Hist Med',
    'Can Ethn Stud',
    'Caribb Stud',
    'Cathol Hist Rev',
    'Cellbio',
    'Civ War Hist',
    'Class World',
    'Comput Mol Biosci',
    'Configurations',
    'Creat Educ',
    'Dissent',
    'Early Am Lit',
    'Ehealth Telecommun Syst Netw',
    'Eighteenth Century Stud',
    'Eire Irel',
    'Energy Power Eng',
    'Food Nutr Sci',
    'Forensic Med Anat Res',
    'Future Child',
    'Health',
    'Health N Hav',
    'Hispania',
    'Histoire Soc',
    'Int J Anal Mass Spectrom Cromatogr',
    'Int J Clin Med',
    'Int J Commun Netw Syst Sci',
    'Int J Intell Sci',
    'Int J Med Phys Clin Eng Radiat Oncol',
    'Int J Org Chem',
    'Intell Inf Manag',
    'J Behav Brain Sci',
    'J Biomater Nanobiotechnol',
    'J Biomed Sci Eng',
    'J Biosci Med',
    'J Cancer Ther',
    'J Coll Stud Dev',
    'J Colon Colon Hist',
    'J Diabetes Mellitus',
    'J Early Repub',
    'J Environ Prot',
    'J Hist Ideas',
    'J Hist Philos',
    'J Immune Based Ther Vaccines Antimicrob',
    'J Sens Technol',
    'J South Hist',
    'J Surf Eng Mater Adv Technol',
    'J Transp Technol',
    'J Tuberc Res',
    'J Water Resour Prot',
    'J Womens Hist',
    'James Joyce Q',
    'Jew Q Rev',
    'Kennedy Inst Ethics J',
    'Late Imp China',
    'Libr Trends',
    'Lit Med',
    'Low Carbon Econ',
    'Magic Ritual Witch',
    'Mod Res Inflamm',
    'NWSA J',
    'Nat Sci',
    'Neurosci Med',
    'New Lit Hist',
    'Northeast Afr Stud',
    'Ohio Hist',
    'Open J Anesthesiol',
    'Open J Anim Sci',
    'Open J Apoptosis',
    'Open J Biophys',
    'Open J Clin Diagn',
    'Open J Endocr Metab Dis',
    'Open J Epidemiol',
    'Open J Gastroenterol',
    'Open J Genet',
    'Open J Immunol',
    'Open J Inorg Chem',
    'Open J Med Chem',
    'Open J Med Microbiol',
    'Open J Med Psychol',
    'Open J Mod Linguist',
    'Open J Mol Integr Physiol',
    'Open J Nephrol',
    'Open J Nurs',
    'Open J Obstet Gynecol',
    'Open J Ophthalmol',
    'Open J Orthop',
    'Open J Pediatr',
    'Open J Philos',
    'Open J Phys Chem',
    'Open J Polit Sci',
    'Open J Prev Med',
    'Open J Psychiatr',
    'Open J Radiol',
    'Open J Rheumatol Autoimmune Dis',
    'Open J Soc Sci',
    'Open J Stat',
    'Open J Stomatol',
    'Open J Vet Med',
    'Parergon',
    'Perspect Biol Med',
    'Pharmacol Pharm',
    'Philos East West',
    'Psychol Educ',
    'Psychology',
    'Quaker Hist',
    'Rev Am Hist',
    'Soc Netw',
    'Southwest Hist Q',
    'Stud Eighteenth Cent Cult',
    'Stud Engl Lit',
    'Surg Sci',
    'Technol Cult',
    'Technol Invest',
    'Thomist',
    'Vic Stud',
    'World J AIDS',
    'World J Cardiovasc Dis',
    'World J Cardiovasc Surg',
    'World J Neurosci',
    'World J Vaccines',
    'World Polit'
)