"""Thieme Medical Publishers journals.

Thieme is a German medical and scientific publisher with a long history of publishing
high-quality journals in medicine, health sciences, and related fields.

Their journals are hosted on thieme-connect.de and use DOI-based PDF access.

Based on investigation, their PDF access pattern is:
https://www.thieme-connect.de/products/ejournals/pdf/{doi}.pdf

DOI pattern: Thieme uses 10.1055 as their DOI prefix.
"""

# DOI-based template for Thieme Connect (evidence-driven pattern)
# Evidence from HTML samples shows http://www.thieme-connect.de pattern
thieme_doi_format = 'http://www.thieme-connect.de/products/ejournals/pdf/{doi}.pdf'


# Thieme journals from categorized analysis
# These journals showed up as associated with thieme-connect.de domain
thieme_journals = [
    'ACI open',
    'AIMS Genet',
    'AJP Rep',
    'Aktuelle Urol',
    'Am J Perinatol',
    'Anasthesiol Intensivmed Notfallmed Schmerzther',
    'Ann Natl Acad Med Sci',
    'Aorta (Stamford)',
    'Appl Clin Inform',
    'Arch Plast Surg',
    'Arq Neuropsiquiatr',
    'Asian J Neurosurg',
    'Avicenna J Med',
    'Br Homeopath J',
    'Cent Eur Neurosurg',
    'Clin Colon Rectal Surg',
    'Dig Dis Interv',
    'Dtsch Med Wochenschr',
    'Endosc Int Open',
    'Endoscopy',
    'Eur J Dent',
    'Eur J Pediatr Surg',
    'European J Gen Dent',
    'European J Pediatr Surg Rep',
    'Evid Based Spine Care J',
    'Exp Clin Endocrinol',
    'Facial Plast Surg',
    'Fortschr Neurol Psychiatr',
    'Fortschr Neurol Psychiatr Grenzgeb',
    'Geburtshilfe Frauenheilkd',
    'Gesundheitswesen',
    'Glob Med Genet',
    'Hamostaseologie',
    'Handchir Mikrochir Plast Chir',
    'Indian J Med Paediatr Oncol',
    'Int Arch Otorhinolaryngol',
    'Int J Angiol',
    'Int J Epilepsy',
    'J Acad Ophthalmol (2017)',
    'J Brachial Plex Peripher Nerve Inj',
    'J Knee Surg',
    'J Neuroanaesth Crit Care',
    'J Neurol Surg A Cent Eur Neurosurg',
    'J Neurol Surg B Skull Base',
    'J Neurol Surg Rep',
    'J Pediatr Biochem',
    'J Pediatr Epilepsy',
    'J Pediatr Genet',
    'J Pediatr Infect Dis',
    'J Pediatr Intensive Care',
    'J Pediatr Neurol',
    'J Reconstr Microsurg',
    'J Wrist Surg',
    'Joints',
    'Klin Monbl Augenheilkd',
    'Klin Padiatr',
    'Laryngorhinootologie',
    'Methods Inf Med',
    'Minim Invasive Neurosurg',
    'Neurochirurgia (Stuttg)',
    'Neuropadiatrie',
    'Nuklearmedizin',
    'Pharmakopsychiatr Neuropsychopharmakol',
    'Pharmacopsychiatria',
    'Pharmacopsychiatry',
    'Planta Med',
    'Pneumologie',
    'Psychiatr Prax',
    'Psychother Psychosom Med Psychol',
    'Rehabilitation',
    'Rehabilitation (Stuttg)',
    'Rev Bras Ortop (Sao Paulo)',
    'Rofo',
    'Semin Hear',
    'Semin Intervent Radiol',
    'Semin Liver Dis',
    'Semin Musculoskelet Radiol',
    'Semin Neurol',
    'Semin Plast Surg',
    'Semin Reprod Endocrinol',
    'Semin Reprod Med',
    'Semin Respir Crit Care Med',
    'Semin Speech Lang',
    'Semin Thromb Hemost',
    'Skull Base',
    'Skull Base Rep',
    'Skull Base Surg',
    'Sleep Sci',
    'South Asian J Cancer',
    'Sports Med Int Open',
    'Sportverletz Sportschaden',
    'Surg J (N Y)',
    'Synlett',
    'Synthesis (Stuttg)',
    'TH Open',
    'Thorac Cardiovasc Surg',
    'Thorac Cardiovasc Surg Rep',
    'Thoraxchir Vask Chir',
    'Thoraxchir Vask Chir (1962)',
    'Tierarztl Prax Ausg G Grosstiere Nutztiere',
    'Tierarztl Prax Ausg K Kleintiere Heimtiere',
    'Ultraschall Med',
    'Ultrasound Int Open',
    'Vet Comp Orthop Traumatol',
    'World J Nucl Med',
    'Yearb Med Inform',
    'Z Gastroenterol',
    'Z Geburtshilfe Neonatol',
    'Z Kinderchir',
    'Z Orthop Ihre Grenzgeb',
    'Z Orthop Unfall',
    'Zentralbl Chir',
    'Zentralbl Gynakol',
    'Zentralbl Neurochir',
]